// 패턴 카드. 변형 문장 순서는 사용 빈도 "추정" 순 (코퍼스 검증 전).
// cat: daily | travel | service | office   tone: casual | neutral | polite
// key: 롤플레이에서 패턴을 썼는지 볼 때 찾는 구절 (여러 개면 배열)
// sit: 목록에서 묶어 보여줄 상황. 순서는 아래 SITS를 따른다
const SITS = {
  daily: ['카페·식당', '쇼핑', '약속·계획', '스몰토크·근황', '리액션·맞장구', '감정·의견', '부탁·거절'],
  travel: ['공항·기내', '호텔', '길 찾기·교통', '관광·예약', '문제 생겼을 때'],
  service: ['맞이하기·용건 확인', '안내·설명', '기다리게 할 때', '사과·불만 대응', '결제·마무리'],
  office: ['동료 스몰토크', '의견 말하기', '동의·반대', '되묻기·확인', '업무 요청', '진행 보고', '일정 조율', '화상회의'],
};
const CARDS = [
  // ── 일상 ──
  { id: 'can-i-get', cat: 'daily', sit: '카페·식당', tone: 'neutral', pattern: 'Can I get ___?', key: 'can i get',
    ko: '~ 주세요', when: '주문하거나 뭔가를 요청할 때 가장 무난한 표현',
    tip: '"Give me ___"는 명령처럼 들려서 무례하게 느껴질 수 있어요.',
    variants: [
      { en: 'Can I get an iced americano?', ko: '아이스 아메리카노 한 잔 주세요.',
        link: { text: 'Can‿I get‿an‿iced americano?', sound: 'kə-nai ge-də-NAIST ə-me-ri-KA-no', rules: ['link', 'flap', 'weak'] } },
      { en: 'Can I get this to go?', ko: '이거 포장해 주세요.',
        link: { text: 'Can‿I ge(t) this to go?', sound: 'kə-nai ge(t) THIS tə GO', rules: ['link', 'stop', 'weak'] } },
      { en: 'Can I get the check?', ko: '계산서 주세요.',
        link: { text: 'Can‿I ge(t) the check?', sound: 'kə-nai ge(t) thə CHECK', rules: ['link', 'stop', 'weak'] } }],
    roleplay: { tutor: 'Hi! What can I get for you?', ko: '안녕하세요! 뭘 드릴까요?', answer: 'Can I get a latte, please?' } },
  { id: 'do-you-have', cat: 'daily', sit: '쇼핑', tone: 'neutral', pattern: 'Do you have ___?', key: 'do you have',
    ko: '~ 있어요?', when: '가게에서 물건이나 옵션을 물어볼 때',
    variants: [
      { en: 'Do you have this in a smaller size?', ko: '이거 더 작은 사이즈 있어요?' },
      { en: 'Do you have any vegetarian options?', ko: '채식 메뉴 있어요?' },
      { en: 'Do you have Wi-Fi here?', ko: '여기 와이파이 돼요?' }],
    roleplay: { tutor: 'Anything I can help you find?', ko: '찾으시는 거 있으세요?', answer: 'Do you have this in black?' } },
  { id: 'are-you-free', cat: 'daily', sit: '약속·계획', tone: 'casual', pattern: 'Are you free ___?', key: 'are you free',
    ko: '~ 시간 돼?', when: '약속을 잡을 때',
    variants: [
      { en: 'Are you free this weekend?', ko: '이번 주말에 시간 돼?' },
      { en: 'Are you free for lunch tomorrow?', ko: '내일 점심 같이 할 시간 돼?' },
      { en: 'Are you free to talk now?', ko: '지금 얘기할 수 있어?' }],
    roleplay: { tutor: 'We should hang out sometime!', ko: '언제 한번 놀자!', answer: 'Totally! Are you free this Saturday?' } },
  { id: 'how-about', cat: 'daily', sit: '약속·계획', tone: 'casual', pattern: 'How about ___?', key: 'how about',
    ko: '~ 어때?', when: '제안하거나 다른 안을 낼 때',
    variants: [
      { en: 'How about 7?', ko: '7시 어때?' },
      { en: 'How about we grab dinner instead?', ko: '대신 저녁 먹는 건 어때?' },
      { en: 'How about next Friday?', ko: '다음 주 금요일 어때?' }],
    roleplay: { tutor: "I can't do Thursday. Sorry!", ko: '목요일은 안 돼. 미안!', answer: 'No worries. How about Friday?' } },
  { id: 'im-down', cat: 'daily', sit: '약속·계획', tone: 'casual', pattern: "I'm down for ___.", key: "i'm down",
    ko: '~ 좋아, 콜', when: '제안에 흔쾌히 동의할 때. 20~30대가 많이 써요',
    tip: '"I\'m feeling down"(우울해)과 뜻이 정반대예요. 회사에서는 쓰지 마세요.',
    variants: [
      { en: "I'm down for that.", ko: '그거 좋아.' },
      { en: "I'm down for tacos.", ko: '타코 콜.' },
      { en: "I'm down to hang out tonight.", ko: '오늘 밤 놀 수 있어.' }],
    roleplay: { tutor: 'Wanna grab some drinks after work?', ko: '퇴근하고 한잔할래?', answer: "I'm down for that!" } },
  { id: 'how-was-your', cat: 'daily', sit: '스몰토크·근황', tone: 'casual', pattern: 'How was your ___?', key: 'how was your',
    ko: '~ 어땠어?', when: '스몰토크를 시작할 때',
    variants: [
      { en: 'How was your weekend?', ko: '주말 어땠어?' },
      { en: 'How was your trip?', ko: '여행 어땠어?' },
      { en: 'How was your day?', ko: '오늘 하루 어땠어?' }],
    roleplay: { tutor: 'Hey, I just got back from Hawaii!', ko: '나 하와이 갔다가 방금 왔어!', answer: 'No way! How was your trip?' } },
  { id: 'ive-been-lately', cat: 'daily', sit: '스몰토크·근황', tone: 'casual', pattern: "I've been ___ lately.", key: "i've been",
    ko: '요즘 ~하고 있어', when: '근황을 말할 때',
    variants: [
      { en: "I've been really busy lately.", ko: '요즘 정말 바빴어.' },
      { en: "I've been working out a lot lately.", ko: '요즘 운동 많이 하고 있어.' },
      { en: "I've been into cooking lately.", ko: '요즘 요리에 빠졌어.' }],
    roleplay: { tutor: "Long time no see! What's new with you?", ko: '오랜만이야! 요즘 어떻게 지내?', answer: "I've been really busy with work lately." } },
  { id: 'not-really-into', cat: 'daily', sit: '감정·의견', tone: 'casual', pattern: "I'm not really into ___.", key: 'not really into',
    ko: '~는 별로 안 좋아해', when: '취향을 부드럽게 거절할 때',
    tip: '"I don\'t like ___"보다 부드럽게 들려요.',
    variants: [
      { en: "I'm not really into horror movies.", ko: '공포 영화는 별로야.' },
      { en: "I'm not really into sports.", ko: '스포츠는 별로 안 좋아해.' },
      { en: "I'm not really into spicy food.", ko: '매운 음식은 별로야.' }],
    roleplay: { tutor: 'Do you wanna watch a horror movie tonight?', ko: '오늘 밤에 공포 영화 볼래?', answer: "Hmm, I'm not really into horror movies." } },
  { id: 'that-sounds', cat: 'daily', sit: '리액션·맞장구', tone: 'casual', pattern: 'That sounds ___.', key: 'that sounds',
    ko: '그거 ~하겠다', when: '상대 말에 리액션할 때. 회화에서 가장 자주 쓰는 편',
    tip: '명사 앞에는 like를 붙여요. (That sounds like a plan.)',
    variants: [
      { en: 'That sounds fun.', ko: '재밌겠다.' },
      { en: 'That sounds rough.', ko: '힘들었겠다.' },
      { en: 'That sounds like a plan.', ko: '좋아, 그렇게 하자.' }],
    roleplay: { tutor: 'I had to work until midnight yesterday.', ko: '어제 자정까지 일했어.', answer: 'Oh no, that sounds rough.' } },
  { id: 'i-feel-like', cat: 'daily', sit: '감정·의견', tone: 'casual', pattern: 'I feel like ___.', key: 'i feel like',
    ko: '~가 당겨 / ~인 것 같아', when: '먹고 싶은 것, 몸 상태, 예감을 말할 때',
    tip: '뒤에 명사가 오면 "~가 당긴다"는 뜻이에요.',
    variants: [
      { en: 'I feel like pizza tonight.', ko: '오늘 밤은 피자가 당겨.' },
      { en: "I feel like I'm getting sick.", ko: '감기 걸리려나 봐.' },
      { en: "I feel like it's gonna rain.", ko: '비 올 것 같아.' }],
    roleplay: { tutor: 'What do you wanna eat tonight?', ko: '오늘 저녁 뭐 먹고 싶어?', answer: 'I feel like Korean food.' } },
  { id: 'ill-have', cat: 'daily', sit: '카페·식당', tone: 'neutral', pattern: "I'll have ___.", key: "i'll have",
    ko: '~로 할게요', when: '메뉴를 고르고 주문을 확정할 때',
    variants: [
      { en: "I'll have the same.", ko: '저도 같은 걸로 할게요.',
        link: { text: "I'll‿have the same.", sound: 'ai-ləv thə SAME', rules: ['weak', 'link'] } },
      { en: "I'll have the chicken salad.", ko: '치킨 샐러드로 할게요.',
        link: { text: "I'll‿have the chicken salad.", sound: 'ai-ləv thə CHI-kən SA-ləd', rules: ['weak', 'link'] } },
      { en: "I'll have a medium latte with oat milk.", ko: '미디엄 라테에 귀리 우유로 할게요.',
        link: { text: "I'll‿have‿a medium latte with‿oat milk.", sound: 'ai-lə-və MEE-dee-əm LA-dei wi-thoat MILK', rules: ['weak', 'link', 'flap'] } }],
    roleplay: { tutor: 'Are you ready to order?', ko: '주문하시겠어요?', answer: "Yes, I'll have the chicken salad, please." } },
  { id: 'can-we-sit', cat: 'daily', sit: '카페·식당', tone: 'neutral', pattern: 'Can we sit ___?', key: 'can we sit',
    ko: '~에 앉아도 될까요?', when: '식당에서 자리를 고를 때',
    variants: [
      { en: 'Can we sit outside?', ko: '밖에 앉아도 될까요?',
        link: { text: 'Can we sit‿outside?', sound: 'kən wee si-dout-SIDE', rules: ['weak', 'link', 'flap'] } },
      { en: 'Can we sit by the window?', ko: '창가에 앉아도 될까요?',
        link: { text: 'Can we si(t) by the window?', sound: 'kən wee SI(t) bai thə WIN-dou', rules: ['weak', 'stop'] } },
      { en: 'Can we sit at the bar?', ko: '바 자리에 앉아도 될까요?',
        link: { text: 'Can we sit‿a(t) the bar?', sound: 'kən wee si-də(t) thə BAR', rules: ['weak', 'flap', 'stop'] } }],
    roleplay: { tutor: 'Hi, how many?', ko: '안녕하세요, 몇 분이세요?', answer: 'Two. Can we sit by the window?' } },
  { id: 'looking-for', cat: 'daily', sit: '쇼핑', tone: 'neutral', pattern: "I'm looking for ___.", key: "i'm looking for",
    ko: '~를 찾고 있어요', when: '매장에서 찾는 물건을 말할 때',
    tip: '그냥 둘러볼 때는 "I\'m just looking, thanks."라고 하면 돼요.',
    variants: [
      { en: "I'm looking for a gift for my mom.", ko: '엄마 선물을 찾고 있어요.',
        link: { text: "I'm looking for‿a gift for my mom.", sound: 'aim LOO-king fə-rə GIFT fər mai MOM', rules: ['weak', 'link'] } },
      { en: "I'm looking for a charger for this phone.", ko: '이 폰에 맞는 충전기를 찾고 있어요.',
        link: { text: "I'm looking for‿a charger for this phone.", sound: 'aim LOO-king fə-rə CHAR-jər fər this PHONE', rules: ['weak', 'link'] } },
      { en: "I'm looking for something a little cheaper.", ko: '조금 더 싼 걸 찾고 있어요.',
        link: { text: "I'm looking for something‿a little cheaper.", sound: 'aim LOO-king fər SUM-thing-ə LI-dəl CHEE-pər', rules: ['weak', 'link', 'flap'] } }],
    roleplay: { tutor: 'Hi! Can I help you find anything?', ko: '찾으시는 거 도와드릴까요?', answer: "Yes, I'm looking for a gift for my mom." } },
  { id: 'try-on', cat: 'daily', sit: '쇼핑', tone: 'neutral', pattern: 'Can I try ___ on?', key: 'can i try',
    ko: '~ 입어 봐도 돼요?', when: '옷이나 신발을 입어 보거나 신어 보고 싶을 때',
    tip: 'this, it, them은 try와 on 사이에 넣어요. "try on this"는 어색해요.',
    variants: [
      { en: 'Can I try this on?', ko: '이거 입어 봐도 돼요?',
        link: { text: 'Can‿I try this‿on?', sound: 'kə-nai TRAI thi-SON', rules: ['link', 'weak'] } },
      { en: 'Can I try these on in a smaller size?', ko: '이거 작은 사이즈로 입어 봐도 돼요?',
        link: { text: 'Can‿I try these‿on‿in‿a smaller size?', sound: 'kə-nai TRAI thee-zo-ni-nə SMA-lər SIZE', rules: ['link', 'weak'] } },
      { en: 'Can I try the other one on?', ko: '다른 거 입어 봐도 돼요?',
        link: { text: 'Can‿I try the‿other‿one‿on?', sound: 'kə-nai TRAI thee-YUH-thər WUH-non', rules: ['link', 'glide'] } }],
    roleplay: { tutor: 'Those jeans are on sale today.', ko: '그 청바지 오늘 세일해요.', answer: 'Oh nice. Can I try them on?' } },
  { id: 'any-plans', cat: 'daily', sit: '스몰토크·근황', tone: 'casual', pattern: 'Any plans for ___?', key: 'any plans',
    ko: '~에 계획 있어?', when: '가볍게 대화를 시작할 때',
    tip: '원래는 "Do you have any plans for ~?"인데, 말할 때는 앞을 빼고 이렇게 많이 써요.',
    variants: [
      { en: 'Any plans for the weekend?', ko: '주말에 계획 있어?',
        link: { text: 'Any plans for the weekend?', sound: 'E-nee PLANZ fər thə WEEK-end', rules: ['weak'] } },
      { en: 'Any plans for tonight?', ko: '오늘 밤에 뭐 해?',
        link: { text: 'Any plans for tonight?', sound: 'E-nee PLANZ fər tə-NIGHT', rules: ['weak'] } },
      { en: 'Any plans for the holidays?', ko: '연휴에 계획 있어?',
        link: { text: 'Any plans for the holidays?', sound: 'E-nee PLANZ fər thə HA-lə-deiz', rules: ['weak'] } }],
    roleplay: { tutor: "Finally, it's Friday!", ko: '드디어 금요일이다!', answer: 'I know! Any plans for the weekend?' } },
  { id: 'you-must-be', cat: 'daily', sit: '리액션·맞장구', tone: 'casual', pattern: 'You must be ___.', key: 'you must be',
    ko: '~하겠다', when: '상대 기분을 짐작해서 공감할 때',
    tip: '여기서 must는 "~해야 한다"가 아니라 "분명 ~일 거다"라는 추측이에요.',
    variants: [
      { en: 'You must be tired.', ko: '피곤하겠다.',
        link: { text: 'You mus(t) be tired.', sound: 'yu MUS(t) bee TIRED', rules: ['stop'] } },
      { en: 'You must be so excited.', ko: '엄청 설레겠다.',
        link: { text: 'You mus(t) be so‿excited.', sound: 'yu mus(t) bee SO-wik-SAI-did', rules: ['stop', 'glide', 'flap'] } },
      { en: 'You must be relieved.', ko: '한시름 놨겠다.',
        link: { text: 'You mus(t) be relieved.', sound: 'yu mus(t) bee ri-LEEVD', rules: ['stop'] } }],
    roleplay: { tutor: 'I just finished a twelve-hour shift.', ko: '방금 12시간 근무 끝났어.', answer: 'Wow, you must be exhausted.' } },
  { id: 'i-bet', cat: 'daily', sit: '리액션·맞장구', tone: 'casual', pattern: 'I bet ___.', key: 'i bet',
    ko: '분명 ~했겠다', when: '상대 이야기에 "그랬겠다"고 맞장구칠 때',
    variants: [
      { en: 'I bet it was amazing.', ko: '진짜 좋았겠다.',
        link: { text: 'I bet‿i(t) was‿amazing.', sound: 'ai BE-di(t) wə-zə-MEI-zing', rules: ['flap', 'stop', 'link', 'weak'] } },
      { en: "I bet you're exhausted.", ko: '엄청 지쳤겠다.',
        link: { text: "I bet‿you're‿exhausted.", sound: 'ai BE-chə-rig-ZAWS-tid', rules: ['yu', 'link'] } },
      { en: 'I bet she was surprised.', ko: '그 사람 놀랐겠다.',
        link: { text: 'I be(t) she was surprised.', sound: 'ai BE(t) shee wəz sər-PRIZED', rules: ['stop', 'weak'] } }],
    roleplay: { tutor: 'I saw the Northern Lights in Iceland!', ko: '아이슬란드에서 오로라 봤어!', answer: 'No way! I bet it was amazing.' } },
  { id: 'not-sure', cat: 'daily', sit: '감정·의견', tone: 'neutral', pattern: "I'm not sure ___.", key: "i'm not sure",
    ko: '~인지 잘 모르겠어', when: '단정하지 않고 조심스럽게 말할 때',
    tip: '"I don\'t know"보다 부드럽고, 반대 의견을 돌려 말할 때도 자주 써요.',
    variants: [
      { en: "I'm not sure that's a good idea.", ko: '그게 좋은 생각인지 잘 모르겠어.',
        link: { text: "I'm no(t) sure that's‿a good‿idea.", sound: 'aim NA(t) SHUR tha-tsə GU-dai-DEE-ə', rules: ['stop', 'link'] } },
      { en: "I'm not sure if I can make it.", ko: '갈 수 있을지 모르겠어.',
        link: { text: "I'm no(t) sure‿if‿I can make‿it.", sound: 'aim na(t) SHU-ri-fai kən MAY-kit', rules: ['stop', 'link', 'weak'] } },
      { en: "I'm not sure what you mean.", ko: '무슨 말인지 잘 모르겠어.',
        link: { text: "I'm no(t) sure what‿you mean.", sound: 'aim na(t) SHUR wə-chə MEAN', rules: ['stop', 'yu'] } }],
    roleplay: { tutor: "Let's drive to the beach tonight!", ko: '오늘 밤에 바다로 드라이브 가자!', answer: "Hmm, I'm not sure that's a good idea. It's pretty late." } },
  { id: 'do-me-a-favor', cat: 'daily', sit: '부탁·거절', tone: 'neutral', pattern: 'Could you do me a favor and ___?', key: 'do me a favor',
    ko: '부탁 하나만, ~해 줄래?', when: '친구나 동료에게 부탁할 때',
    variants: [
      { en: 'Could you do me a favor and grab my charger?', ko: '내 충전기 좀 갖다줄래?',
        link: { text: 'Could you do me‿a favor‿and grab my charger?', sound: 'ku-jə DOO mee-ə FEI-vər-ən GRAB mai CHAR-jər', rules: ['yu', 'glide', 'weak', 'link'] } },
      { en: 'Could you do me a favor and watch my bag for a sec?', ko: '잠깐 내 가방 좀 봐줄래?',
        link: { text: 'Could you do me‿a favor‿and watch my bag for‿a sec?', sound: 'ku-jə DOO mee-ə FEI-vər-ən WATCH mai BAG fə-rə SEC', rules: ['yu', 'glide', 'weak', 'link'] } },
      { en: 'Could you do me a favor and text me when you get there?', ko: '도착하면 문자 좀 해줄래?',
        link: { text: 'Could you do me‿a favor‿and tex(t) me when you ge(t) there?', sound: 'ku-jə DOO mee-ə FEI-vər-ən TEKS mee wen yu ge(t) THERE', rules: ['yu', 'glide', 'weak', 'stop'] } }],
    roleplay: { tutor: "I'm heading to the store. Need anything?", ko: '나 가게 가는데, 필요한 거 있어?', answer: 'Yeah, could you do me a favor and grab some milk?' } },
  { id: 'do-you-mind-if', cat: 'daily', sit: '부탁·거절', tone: 'neutral', pattern: 'Do you mind if I ___?', key: 'do you mind if',
    ko: '~해도 될까요?', when: '허락을 구할 때',
    tip: '"No"라고 답해야 "괜찮아요(신경 안 써요)"라는 뜻이에요. "Yes"는 "싫어요"가 돼요. 보통 "Not at all"이나 "Go ahead"라고 답해요.',
    variants: [
      { en: 'Do you mind if I open the window?', ko: '창문 좀 열어도 될까요?',
        link: { text: 'Do you mind‿if‿I‿open the window?', sound: 'də-yə MIN-di-fai-YOU-pən thə WIN-dou', rules: ['weak', 'link', 'glide'] } },
      { en: 'Do you mind if I join you?', ko: '같이 껴도 될까요?',
        link: { text: 'Do you mind‿if‿I join you?', sound: 'də-yə MIN-di-fai JOIN yu', rules: ['weak', 'link'] } },
      { en: 'Do you mind if I bring a friend?', ko: '친구 한 명 데려가도 될까?',
        link: { text: 'Do you mind‿if‿I bring‿a friend?', sound: 'də-yə MIN-di-fai BRING-ə FREND', rules: ['weak', 'link'] } }],
    roleplay: { tutor: 'Come on in! Make yourself at home.', ko: '들어와! 편하게 있어.', answer: 'Thanks! Do you mind if I open the window?' } },
  { id: 'love-to-but', cat: 'daily', sit: '부탁·거절', tone: 'casual', pattern: "I'd love to, but ___.", key: "i'd love to",
    ko: '정말 그러고 싶은데, ~', when: '초대나 제안을 부드럽게 거절할 때',
    tip: '거절 뒤에 "Maybe next time?"을 붙이면 더 자연스러워요.',
    variants: [
      { en: "I'd love to, but I already have plans.", ko: '가고 싶은데 이미 약속이 있어.',
        link: { text: "I'd love to, but‿I‿already have plans.", sound: 'aid LUV tə, bə-dai-yawl-RE-dee hav PLANZ', rules: ['weak', 'flap', 'glide'] } },
      { en: "I'd love to, but I'm swamped this week.", ko: '그러고 싶은데 이번 주엔 일이 너무 많아.',
        link: { text: "I'd love to, but‿I'm swamped this week.", sound: 'aid LUV tə, bə-daim SWAMPT this WEEK', rules: ['weak', 'flap'] } },
      { en: "I'd love to, but I can't tonight.", ko: '그러고 싶은데 오늘 밤은 안 돼.',
        link: { text: "I'd love to, but‿I can'(t) tonight.", sound: 'aid LUV tə, bə-dai KAN(t) tə-NIGHT', rules: ['weak', 'flap', 'stop'] } }],
    roleplay: { tutor: "We're going bowling tonight. Wanna come?", ko: '오늘 밤에 볼링 치러 가는데, 올래?', answer: "I'd love to, but I already have plans. Maybe next time?" } },

  // ── 여행 ──
  { id: 'is-there-around', cat: 'travel', sit: '길 찾기·교통', tone: 'neutral', pattern: 'Is there ___ around here?', key: 'is there',
    ko: '이 근처에 ~ 있어요?', when: '길에서 장소를 찾을 때',
    variants: [
      { en: 'Is there a pharmacy around here?', ko: '이 근처에 약국 있어요?' },
      { en: 'Is there a subway station nearby?', ko: '근처에 지하철역 있어요?' },
      { en: 'Is there a good place to eat around here?', ko: '이 근처에 괜찮은 식당 있어요?' }],
    roleplay: { tutor: 'Hi there, can I help you with something?', ko: '도와드릴까요?', answer: 'Yes, is there an ATM around here?' } },
  { id: 'how-do-i-get-to', cat: 'travel', sit: '길 찾기·교통', tone: 'neutral', pattern: 'How do I get to ___?', key: 'how do i get to',
    ko: '~에 어떻게 가요?', when: '길을 물을 때',
    variants: [
      { en: 'How do I get to the airport?', ko: '공항에 어떻게 가요?' },
      { en: 'How do I get to Times Square from here?', ko: '여기서 타임스스퀘어 어떻게 가요?' },
      { en: 'How do I get to Gate 12?', ko: '12번 게이트 어떻게 가요?' }],
    roleplay: { tutor: 'You look lost. Where are you headed?', ko: '길 잃으신 것 같네요. 어디 가세요?', answer: 'How do I get to Central Park?' } },
  { id: 'id-like-to', cat: 'travel', sit: '호텔', tone: 'polite', pattern: "I'd like to ___.", key: "i'd like to",
    ko: '~하고 싶습니다', when: '호텔·공항에서 요청할 때',
    tip: '"I want to ___"보다 정중해요. 호텔·공항에서는 이걸 기본으로 쓰세요.',
    variants: [
      { en: "I'd like to check in.", ko: '체크인하려고요.' },
      { en: "I'd like to change my seat.", ko: '좌석을 바꾸고 싶어요.' },
      { en: "I'd like to stay one more night.", ko: '하룻밤 더 묵고 싶어요.' }],
    roleplay: { tutor: 'Good evening! How can I help you?', ko: '안녕하세요! 무엇을 도와드릴까요?', answer: "Hi, I'd like to check in. The reservation is under Kim." } },
  { id: 'is-it-okay-if', cat: 'travel', sit: '호텔', tone: 'neutral', pattern: 'Is it okay if ___?', key: 'is it okay if',
    ko: '~해도 괜찮을까요?', when: '허락을 구할 때',
    variants: [
      { en: 'Is it okay if I leave my bags here?', ko: '짐을 여기 둬도 될까요?',
        link: { text: 'Is‿it‿okay‿if‿I leave my bags here?', sound: 'i-zi-dou-KAY-yi-fai LEAVE mai BAGZ heer', rules: ['link', 'flap', 'glide'] } },
      { en: 'Is it okay if I sit here?', ko: '여기 앉아도 될까요?',
        link: { text: 'Is‿it‿okay‿if‿I si(t) here?', sound: 'i-zi-dou-KAY-yi-fai SI(t) heer', rules: ['link', 'flap', 'glide', 'stop'] } },
      { en: 'Is it okay if I pay by card?', ko: '카드로 계산해도 될까요?',
        link: { text: 'Is‿it‿okay‿if‿I pay by card?', sound: 'i-zi-dou-KAY-yi-fai PAY bai CARD', rules: ['link', 'flap', 'glide'] } }],
    roleplay: { tutor: 'Checkout is at 11. Anything else?', ko: '체크아웃은 11시예요. 더 필요하신 거 있으세요?', answer: 'Is it okay if I leave my bags here after checkout?' } },
  { id: 'problem-with', cat: 'travel', sit: '문제 생겼을 때', tone: 'polite', pattern: "I think there's a problem with ___.", key: "there's a problem with",
    ko: '~에 문제가 있는 것 같아요', when: '방, 예약, 계산서에 문제가 있을 때',
    tip: '"I think"로 시작하면 따지는 느낌이 줄어요.',
    variants: [
      { en: "I think there's a problem with my room.", ko: '방에 문제가 있는 것 같아요.' },
      { en: "I think there's a problem with my reservation.", ko: '예약에 문제가 있는 것 같아요.' },
      { en: "I think there's a problem with the bill.", ko: '계산서가 잘못된 것 같아요.' }],
    roleplay: { tutor: 'Is everything okay with your stay?', ko: '지내시는 데 불편한 건 없으세요?', answer: "Actually, I think there's a problem with the air conditioner." } },
  { id: 'line-for', cat: 'travel', sit: '공항·기내', tone: 'neutral', pattern: 'Is this the line for ___?', key: 'is this the line',
    ko: '~ 줄이 여기 맞아요?', when: '공항이나 관광지에서 줄을 제대로 섰는지 확인할 때',
    variants: [
      { en: 'Is this the line for security?', ko: '보안 검색 줄 여기 맞아요?',
        link: { text: 'Is this the line for security?', sound: 'iz THIS thə LINE fər sə-KYUR-ə-dee', rules: ['weak', 'flap'] } },
      { en: 'Is this the line for check-in?', ko: '체크인 줄 여기 맞아요?',
        link: { text: 'Is this the line for check‿in?', sound: 'iz THIS thə LINE fər CHE-kin', rules: ['weak', 'link'] } },
      { en: 'Is this the line for the shuttle?', ko: '셔틀 타는 줄 여기 맞아요?',
        link: { text: 'Is this the line for the shuttle?', sound: 'iz THIS thə LINE fər thə SHUH-dəl', rules: ['weak', 'flap'] } }],
    roleplay: { tutor: 'Excuse me, are you in line?', ko: '실례지만, 줄 서 계신 거예요?', answer: 'Yes. Is this the line for check-in?' } },
  { id: 'im-staying', cat: 'travel', sit: '공항·기내', tone: 'neutral', pattern: "I'm staying ___.", key: "i'm staying",
    ko: '~에 묵어요 / ~ 동안 머물러요', when: '입국 심사에서 숙소나 기간을 물을 때',
    tip: '입국 심사에서는 짧고 분명하게 답하는 게 좋아요. 숙소 이름을 미리 외워 두세요.',
    variants: [
      { en: "I'm staying at the Hilton downtown.", ko: '시내 힐튼 호텔에 묵어요.',
        link: { text: "I'm staying‿at the Hilton downtown.", sound: 'aim STAY-ing-ət thə HIL-tən down-TOWN', rules: ['link', 'weak'] } },
      { en: "I'm staying for ten days.", ko: '열흘 동안 머물러요.',
        link: { text: "I'm staying for ten days.", sound: 'aim STAY-ing fər TEN DAYZ', rules: ['weak'] } },
      { en: "I'm staying with a friend.", ko: '친구 집에 묵어요.',
        link: { text: "I'm staying with‿a friend.", sound: 'aim STAY-ing wi-thə FREND', rules: ['link', 'weak'] } }],
    roleplay: { tutor: 'Where will you be staying?', ko: '어디서 묵으실 건가요?', answer: "I'm staying at the Hilton downtown." } },
  { id: 'would-it-be-possible', cat: 'travel', sit: '공항·기내', tone: 'polite', pattern: 'Would it be possible to ___?', key: 'would it be possible',
    ko: '~할 수 있을까요?', when: '카운터나 기내에서 정중하게 요청할 때',
    tip: '"Can I ~?"보다 한 단계 더 정중해요. 들어주기 어려운 부탁일수록 이걸 쓰세요.',
    variants: [
      { en: 'Would it be possible to get an aisle seat?', ko: '통로 쪽 좌석으로 받을 수 있을까요?',
        link: { text: 'Would‿i(t) be possible to get‿an‿aisle seat?', sound: 'wu-di(t) bee PA-sə-bəl tə ge-də-NAIL SEAT', rules: ['link', 'stop', 'weak', 'flap'] } },
      { en: 'Would it be possible to switch seats?', ko: '자리를 바꿀 수 있을까요?',
        link: { text: 'Would‿i(t) be possible to switch seats?', sound: 'wu-di(t) bee PA-sə-bəl tə SWITCH SEATS', rules: ['link', 'stop', 'weak'] } },
      { en: 'Would it be possible to get an extra blanket?', ko: '담요 하나 더 받을 수 있을까요?',
        link: { text: 'Would‿i(t) be possible to get‿an‿extra blanket?', sound: 'wu-di(t) bee PA-sə-bəl tə ge-də-NEK-strə BLAN-kit', rules: ['link', 'stop', 'weak', 'flap'] } }],
    roleplay: { tutor: "Here's your boarding pass. Anything else?", ko: '탑승권 여기 있습니다. 더 필요하신 거 있으세요?', answer: 'Would it be possible to get an aisle seat?' } },
  { id: 'what-time-does', cat: 'travel', sit: '호텔', tone: 'neutral', pattern: 'What time does ___?', key: 'what time does',
    ko: '~ 몇 시에 해요?', when: '호텔 시설이나 교통편 시간을 물을 때',
    variants: [
      { en: 'What time does breakfast start?', ko: '조식은 몇 시에 시작해요?',
        link: { text: 'Wha(t) time does breakfast start?', sound: 'wə TIME dəz BREK-fəst START', rules: ['same', 'weak'] } },
      { en: 'What time does the pool close?', ko: '수영장은 몇 시에 닫아요?',
        link: { text: 'Wha(t) time does the pool close?', sound: 'wə TIME dəz thə POOL CLOSE', rules: ['same', 'weak'] } },
      { en: 'What time does the shuttle leave?', ko: '셔틀은 몇 시에 출발해요?',
        link: { text: 'Wha(t) time does the shuttle leave?', sound: 'wə TIME dəz thə SHUH-dəl LEAVE', rules: ['same', 'weak', 'flap'] } }],
    roleplay: { tutor: "Here's your key card. Enjoy your stay!", ko: '키 카드 여기 있습니다. 즐거운 시간 되세요!', answer: 'Thanks! What time does breakfast start?' } },
  { id: 'which-should-i-take', cat: 'travel', sit: '길 찾기·교통', tone: 'neutral', pattern: 'Which ___ should I take?', key: 'should i take',
    ko: '어느 ~를 타야 해요?', when: '버스·지하철 노선이나 출구를 고를 때',
    variants: [
      { en: 'Which bus should I take to get downtown?', ko: '시내 가려면 어느 버스 타야 해요?',
        link: { text: 'Which bus should‿I take to ge(t) downtown?', sound: 'wich BUS shu-dai TAKE tə ge(t) down-TOWN', rules: ['link', 'weak', 'stop'] } },
      { en: 'Which exit should I take?', ko: '어느 출구로 나가야 해요?',
        link: { text: 'Which‿exit should‿I take?', sound: 'wi-CHEK-sit shu-dai TAKE', rules: ['link'] } },
      { en: 'Which line should I take to the airport?', ko: '공항 가려면 몇 호선 타야 해요?',
        link: { text: 'Which line should‿I take to the‿airport?', sound: 'wich LINE shu-dai TAKE tə thee-YAIR-port', rules: ['link', 'weak', 'glide'] } }],
    roleplay: { tutor: "You want to go to the museum? It's pretty far from here.", ko: '박물관 가시려고요? 여기서 꽤 멀어요.', answer: 'Oh really? Which bus should I take?' } },
  { id: 'do-i-need', cat: 'travel', sit: '관광·예약', tone: 'neutral', pattern: 'Do I need ___?', key: 'do i need',
    ko: '~ 필요해요?', when: '예약이나 표가 필요한지 물을 때',
    variants: [
      { en: 'Do I need a reservation?', ko: '예약해야 하나요?',
        link: { text: 'Do‿I need‿a reservation?', sound: 'də-wai NEE-də re-zər-VAY-shən', rules: ['glide', 'link'] } },
      { en: 'Do I need to book in advance?', ko: '미리 예약해야 하나요?',
        link: { text: 'Do‿I need to book‿in‿advance?', sound: 'də-wai NEE-tə BOO-kin-əd-VANCE', rules: ['glide', 'link', 'weak'] } },
      { en: 'Do I need a ticket for this?', ko: '이거 표가 필요해요?',
        link: { text: 'Do‿I need‿a ticket for this?', sound: 'də-wai NEE-də TI-kit fər THIS', rules: ['glide', 'link', 'weak'] } }],
    roleplay: { tutor: 'Welcome to the museum!', ko: '박물관에 오신 걸 환영해요!', answer: 'Hi! Do I need a ticket for the special exhibit?' } },
  { id: 'would-you-mind-taking', cat: 'travel', sit: '관광·예약', tone: 'neutral', pattern: 'Would you mind taking ___?', key: 'would you mind',
    ko: '~ 찍어 주실 수 있어요?', when: '사진을 부탁할 때',
    tip: '"Do you mind if I ~?"처럼 "No problem"이나 "Not at all"이 "괜찮아요, 해 줄게요"라는 뜻이에요.',
    variants: [
      { en: 'Would you mind taking a picture of us?', ko: '저희 사진 좀 찍어 주실래요?',
        link: { text: 'Would you mind taking‿a picture‿of‿us?', sound: 'wu-jə MIND TAY-king-ə PIK-chə-rə-vəs', rules: ['yu', 'link', 'weak'] } },
      { en: 'Would you mind taking one more?', ko: '한 장만 더 찍어 주실래요?',
        link: { text: 'Would you mind taking one more?', sound: 'wu-jə MIND TAY-king WUN MORE', rules: ['yu'] } },
      { en: 'Would you mind taking it vertically?', ko: '세로로 찍어 주실래요?',
        link: { text: 'Would you mind taking‿i(t) vertically?', sound: 'wu-jə MIND TAY-king-i(t) VER-di-klee', rules: ['yu', 'link', 'stop', 'flap'] } }],
    roleplay: { tutor: 'Wow, the view from up here is amazing!', ko: '와, 여기서 보는 경치 끝내준다!', answer: 'It really is! Would you mind taking a picture of us?' } },
  { id: 'how-long-take', cat: 'travel', sit: '관광·예약', tone: 'neutral', pattern: 'How long does ___ take?', key: 'how long does',
    ko: '~ 얼마나 걸려요?', when: '소요 시간을 물을 때',
    variants: [
      { en: 'How long does the tour take?', ko: '투어는 얼마나 걸려요?',
        link: { text: 'How long does the tour take?', sound: 'hau LONG dəz thə TOUR TAKE', rules: ['weak'] } },
      { en: 'How long does it take to get there by taxi?', ko: '택시로 거기까지 얼마나 걸려요?',
        link: { text: 'How long does‿i(t) take to ge(t) there by taxi?', sound: 'hau LONG də-zi(t) TAKE tə ge(t) THERE bai TAK-see', rules: ['link', 'stop', 'weak'] } },
      { en: 'How long does the ferry take?', ko: '페리는 얼마나 걸려요?',
        link: { text: 'How long does the ferry take?', sound: 'hau LONG dəz thə FE-ree TAKE', rules: ['weak'] } }],
    roleplay: { tutor: 'The boat tour leaves in ten minutes.', ko: '보트 투어는 10분 뒤에 출발해요.', answer: 'Great. How long does the tour take?' } },
  { id: 'i-lost', cat: 'travel', sit: '문제 생겼을 때', tone: 'neutral', pattern: 'I lost ___.', key: 'i lost',
    ko: '~를 잃어버렸어요', when: '물건을 잃어버렸을 때',
    tip: '분실물 센터를 찾을 때는 "Where\'s the lost and found?"라고 물어요.',
    variants: [
      { en: 'I lost my wallet.', ko: '지갑을 잃어버렸어요.',
        link: { text: 'I los(t) my wallet.', sound: 'ai LOS(t) mai WA-lit', rules: ['stop'] } },
      { en: 'I lost my passport.', ko: '여권을 잃어버렸어요.',
        link: { text: 'I los(t) my passport.', sound: 'ai LOS(t) mai PAS-port', rules: ['stop'] } },
      { en: 'I think I lost my phone on the bus.', ko: '버스에서 폰을 잃어버린 것 같아요.',
        link: { text: 'I think‿I los(t) my phone‿on the bus.', sound: 'ai THING-kai LOS(t) mai FOH-non thə BUS', rules: ['link', 'stop'] } }],
    roleplay: { tutor: 'Hi, what seems to be the problem?', ko: '무슨 문제 있으세요?', answer: 'I lost my passport. I think I left it in a taxi.' } },
  { id: 'i-missed', cat: 'travel', sit: '문제 생겼을 때', tone: 'neutral', pattern: 'I missed ___.', key: 'i missed',
    ko: '~를 놓쳤어요', when: '비행기나 교통편을 놓쳤을 때',
    tip: 'missed의 -ed는 [t]로 소리 나요. [미스드]가 아니라 [미스트]예요.',
    variants: [
      { en: 'I missed my flight.', ko: '비행기를 놓쳤어요.',
        link: { text: 'I missed my flight.', sound: 'ai MIS(t) mai FLIGHT', rules: ['stop'] } },
      { en: 'I missed my connection.', ko: '환승편을 놓쳤어요.',
        link: { text: 'I missed my connection.', sound: 'ai MIS(t) mai kə-NEK-shən', rules: ['stop', 'weak'] } },
      { en: 'I missed the last train.', ko: '막차를 놓쳤어요.',
        link: { text: 'I missed the las(t) train.', sound: 'ai MIS(t) thə LAS(t) TRAIN', rules: ['stop'] } }],
    roleplay: { tutor: 'Oh no, you look stressed. What happened?', ko: '어머, 당황하신 것 같네요. 무슨 일이에요?', answer: 'I missed my flight. When is the next one?' } },

  // ── 회사 · 고객 응대 (매장·호텔) ──
  { id: 'let-me-check', cat: 'service', sit: '안내·설명', tone: 'polite', pattern: 'Let me check ___ for you.', key: 'let me check',
    ko: '확인해 드릴게요', when: '바로 답하기 어려울 때 시간을 버는 표현',
    variants: [
      { en: 'Let me check that for you.', ko: '확인해 드릴게요.' },
      { en: 'Let me check if we have it in stock.', ko: '재고가 있는지 확인해 볼게요.' },
      { en: 'Let me check with my manager.', ko: '매니저에게 확인해 볼게요.' }],
    roleplay: { tutor: 'Do you have this jacket in a medium?', ko: '이 재킷 M 사이즈 있어요?', answer: 'Let me check if we have it in stock.' } },
  { id: 'sorry-for', cat: 'service', sit: '사과·불만 대응', tone: 'polite', pattern: "I'm sorry for ___.", key: ["i'm sorry", "i'm so sorry", 'i apologize'],
    ko: '~해서 죄송합니다', when: '고객에게 사과할 때',
    tip: '"I apologize for ___"가 더 격식 있어요.',
    variants: [
      { en: "I'm sorry for the wait.", ko: '기다리게 해서 죄송합니다.' },
      { en: 'I apologize for the inconvenience.', ko: '불편을 드려 죄송합니다.' },
      { en: "I'm sorry about the mix-up.", ko: '착오가 있었네요. 죄송합니다.' }],
    roleplay: { tutor: "I've been waiting here for twenty minutes!", ko: '여기서 20분이나 기다렸어요!', answer: "I'm so sorry for the wait. Let me check on your order." } },
  { id: 'it-should', cat: 'service', sit: '안내·설명', tone: 'polite', pattern: 'It should ___.', key: 'it should',
    ko: '~일 거예요', when: '시간이나 절차를 안내할 때',
    tip: '"It will"보다 덜 단정적이라, 약속을 못 지킬 위험이 줄어요.',
    variants: [
      { en: 'It should take about 10 minutes.', ko: '10분 정도 걸릴 거예요.' },
      { en: 'It should be ready by 3.', ko: '3시까지는 준비될 거예요.' },
      { en: 'It should arrive within a week.', ko: '일주일 안에 도착할 거예요.' }],
    roleplay: { tutor: 'How long will it take to fix my phone?', ko: '폰 고치는 데 얼마나 걸려요?', answer: 'It should take about an hour.' } },
  { id: 'would-you-like', cat: 'service', sit: '결제·마무리', tone: 'polite', pattern: 'Would you like ___?', key: 'would you like',
    ko: '~ 하시겠어요?', when: '고객에게 뭔가를 제안할 때',
    variants: [
      { en: 'Would you like a receipt?', ko: '영수증 드릴까요?' },
      { en: 'Would you like me to call you a taxi?', ko: '택시 불러 드릴까요?' },
      { en: 'Would you like to wait here?', ko: '여기서 기다리시겠어요?' }],
    roleplay: { tutor: "Okay, I'll take this one.", ko: '이걸로 할게요.', answer: 'Great choice! Would you like a bag?' } },
  { id: 'could-i-get-your', cat: 'service', sit: '맞이하기·용건 확인', tone: 'polite', pattern: 'Could I get your ___?', key: 'could i get your',
    ko: '~ 알려주시겠어요?', when: '고객 정보를 요청할 때',
    variants: [
      { en: 'Could I get your name, please?', ko: '성함 알려주시겠어요?' },
      { en: 'Could I get your phone number?', ko: '전화번호 알려주시겠어요?' },
      { en: 'Could I get your reservation number?', ko: '예약 번호 알려주시겠어요?' }],
    roleplay: { tutor: 'Hi, I have a reservation for tonight.', ko: '오늘 밤 예약했는데요.', answer: 'Sure. Could I get your name, please?' } },

  // ── 회사 · 사내 소통 (외국계) ──
  { id: 'just-to-clarify', cat: 'office', sit: '되묻기·확인', tone: 'neutral', pattern: 'Just to clarify, ___?', key: 'just to clarify',
    ko: '확인차 여쭤보면, ~?', when: '지시나 내용을 다시 확인할 때',
    tip: '못 알아들었을 때 "Sorry?"만 반복하는 것보다 훨씬 프로답게 들려요.',
    variants: [
      { en: 'Just to clarify, the deadline is Friday?', ko: '확인차 여쭤보면, 마감이 금요일이죠?' },
      { en: 'Just to clarify, you want me to send it to the client?', ko: '확인하자면, 이걸 클라이언트에게 보내라는 거죠?' },
      { en: 'Just to clarify, are we meeting in person?', ko: '확인하자면, 대면으로 만나는 거죠?' }],
    roleplay: { tutor: 'Can you send the report to Jake by Friday?', ko: '금요일까지 보고서 Jake한테 보내줄래요?', answer: 'Sure. Just to clarify, the final version or the draft?' } },
  { id: 'i-was-wondering-if', cat: 'office', sit: '업무 요청', tone: 'polite', pattern: 'I was wondering if ___.', key: 'i was wondering if',
    ko: '혹시 ~해도 될까요', when: '부탁하기 어려운 것을 공손하게 요청할 때',
    variants: [
      { en: 'I was wondering if you could take a look at this.', ko: '혹시 이것 좀 봐주실 수 있을까요?' },
      { en: 'I was wondering if I could leave early today.', ko: '혹시 오늘 일찍 퇴근해도 될까요?' },
      { en: 'I was wondering if we could push the meeting.', ko: '혹시 회의를 미룰 수 있을까요?' }],
    roleplay: { tutor: "Hey, what's up?", ko: '무슨 일이에요?', answer: 'I was wondering if you could take a look at my slides.' } },
  { id: 'get-back-to-you', cat: 'office', sit: '진행 보고', tone: 'neutral', pattern: "I'll get back to you ___.", key: 'get back to you',
    ko: '~ 다시 알려드릴게요', when: '당장 답하지 못할 때',
    variants: [
      { en: "I'll get back to you on that.", ko: '그건 확인하고 다시 알려드릴게요.',
        link: { text: "I'll ge(t) back to you‿on that.", sound: 'ail ge(t) BACK tə yu-wan THAT', rules: ['stop', 'weak', 'glide'] } },
      { en: "I'll get back to you by end of day.", ko: '오늘 퇴근 전까지 알려드릴게요.',
        link: { text: "I'll ge(t) back to you by‿end‿of day.", sound: 'ail ge(t) BACK tə yu bai-YEN-də DAY', rules: ['stop', 'weak', 'glide', 'link'] } },
      { en: "I'll get back to you once I hear from them.", ko: '그쪽에서 연락 오면 바로 알려드릴게요.',
        link: { text: "I'll ge(t) back to you once‿I hear from them.", sound: 'ail ge(t) BACK tə yu WAN-sai HEER frəm thəm', rules: ['stop', 'weak', 'link'] } }],
    roleplay: { tutor: 'Do you know when the client will sign?', ko: '클라이언트가 언제 서명할지 알아요?', answer: "Not yet. I'll get back to you once I hear from them." } },
  { id: 'see-your-point', cat: 'office', sit: '동의·반대', tone: 'neutral', pattern: 'I see your point, but ___.', key: 'i see your point',
    ko: '무슨 말인지 알겠는데, ~', when: '회의에서 반대 의견을 낼 때',
    variants: [
      { en: "I see your point, but I'm worried about the timeline.", ko: '무슨 말인지 알겠는데, 일정이 걱정돼요.' },
      { en: 'I see your point, but I think we need more data.', ko: '말씀은 이해하는데, 데이터가 더 필요할 것 같아요.' },
      { en: 'I see your point, but the client might not like it.', ko: '무슨 뜻인지 알겠는데, 클라이언트가 안 좋아할 수도 있어요.' }],
    roleplay: { tutor: 'I think we should launch next week.', ko: '다음 주에 출시하는 게 좋겠어요.', answer: "I see your point, but I'm worried about the timeline." } },
  { id: 'quick-question', cat: 'office', sit: '업무 요청', tone: 'casual', pattern: 'Quick question about ___.', key: 'quick question',
    ko: '~ 관련해서 잠깐 질문', when: '동료에게 가볍게 물어볼 때',
    variants: [
      { en: 'Quick question about the report.', ko: '보고서 관련해서 잠깐 질문이요.' },
      { en: 'Quick question, are we still meeting at 2?', ko: '잠깐만요, 우리 2시 회의 그대로죠?' },
      { en: 'Quick question about the new schedule.', ko: '새 일정 관련해서 잠깐 질문이요.' }],
    roleplay: { tutor: 'Hi! Did you need something?', ko: '뭐 필요한 거 있어요?', answer: 'Yeah, quick question about the report.' } },
];
