CARDS.push(
  { id: 'can-i-get', cat: 'daily', sit: '카페·식당', tone: 'neutral', pattern: 'Can I get ___?', key: 'can i get',
    ko: '~ 주세요', when: '주문하거나 뭔가를 요청할 때 가장 무난한 표현',
    tip: '"Give me ___"는 명령처럼 들려서 무례하게 느껴질 수 있어요.',
    variants: [
      { en: 'Can I get an iced americano?', ko: '아이스 아메리카노 한 잔 주세요.',
        link: { text: 'Can‿I get‿an‿iced americano?', sound: 'kə-nai ge-də-NAIST ə-me-ri-KA-no', rules: ['link', 'flap', 'weak'] } },
      { en: 'Can I get this to go?', ko: '이거 포장해 주세요.',
        link: { text: 'Can‿I ge(t) this to go?', sound: 'kə-nai ge(t) THIS tə GO', rules: ['link', 'stop', 'weak'] } },
      { en: 'Can I get the check?', ko: '계산서 주세요.',
        link: { text: 'Can‿I ge(t) the check?', sound: 'kə-nai ge(t) thə CHECK', rules: ['link', 'stop', 'weak'] } }],
    roleplay: { tutor: 'Hi! What can I get for you?', ko: '안녕하세요! 뭘 드릴까요?', answer: 'Can I get a latte, please?' } },
  { id: 'do-you-have', cat: 'daily', sit: '쇼핑', tone: 'neutral', pattern: 'Do you have ___?', key: 'do you have',
    ko: '~ 있어요?', when: '가게에서 물건이나 옵션을 물어볼 때',
    variants: [
      { en: 'Do you have this in a smaller size?', ko: '이거 더 작은 사이즈 있어요?',
        link: { text: 'Do you have this‿in‿a smaller size?', sound: 'də-yə HAV thi-si-nə SMA-lər SIZE', rules: ['weak', 'link'] } },
      { en: 'Do you have any vegetarian options?', ko: '채식 메뉴 있어요?',
        link: { text: 'Do you have‿any vegetarian‿options?', sound: 'də-yə HA-ve-nee ve-jə-TE-ree-ə-NAP-shənz', rules: ['weak', 'link'] } },
      { en: 'Do you have Wi-Fi here?', ko: '여기 와이파이 돼요?',
        link: { text: 'Do you have Wi-Fi here?', sound: 'də-yə HAV WAI-fai HEER', rules: ['weak'] } }],
    roleplay: { tutor: 'Anything I can help you find?', ko: '찾으시는 거 있으세요?', answer: 'Do you have this in black?' } },
  { id: 'are-you-free', cat: 'daily', sit: '약속·계획', tone: 'casual', pattern: 'Are you free ___?', key: 'are you free',
    ko: '~ 시간 돼?', when: '약속을 잡을 때',
    variants: [
      { en: 'Are you free this weekend?', ko: '이번 주말에 시간 돼?',
        link: { text: 'Are you free this weekend?', sound: 'ar-yə FREE this WEEK-end', rules: ['weak'] } },
      { en: 'Are you free for lunch tomorrow?', ko: '내일 점심 같이 할 시간 돼?',
        link: { text: 'Are you free for lunch tomorrow?', sound: 'ar-yə FREE fər LUNCH tə-MA-roh', rules: ['weak'] } },
      { en: 'Are you free to talk now?', ko: '지금 얘기할 수 있어?',
        link: { text: 'Are you free to talk now?', sound: 'ar-yə FREE tə TALK NOW', rules: ['weak'] } }],
    roleplay: { tutor: 'We should hang out sometime!', ko: '언제 한번 놀자!', answer: 'Totally! Are you free this Saturday?' } },
  { id: 'how-about', cat: 'daily', sit: '약속·계획', tone: 'casual', pattern: 'How about ___?', key: 'how about',
    ko: '~ 어때?', when: '제안하거나 다른 안을 낼 때',
    variants: [
      { en: 'How about 7?', ko: '7시 어때?',
        link: { text: 'How‿abou(t) 7?', sound: 'hau-wə-BOU(t) SE-vən', rules: ['glide', 'stop'] } },
      { en: 'How about we grab dinner instead?', ko: '대신 저녁 먹는 건 어때?',
        link: { text: 'How‿abou(t) we grab dinner‿instead?', sound: 'hau-wə-BOU(t) wee GRAB DI-nə-rin-STED', rules: ['glide', 'stop', 'link'] } },
      { en: 'How about next Friday?', ko: '다음 주 금요일 어때?',
        link: { text: 'How‿abou(t) nex(t) Friday?', sound: 'hau-wə-BOU(t) NEKS FRAI-day', rules: ['glide', 'stop'] } }],
    roleplay: { tutor: "I can't do Thursday. Sorry!", ko: '목요일은 안 돼. 미안!', answer: 'No worries. How about Friday?' } },
  { id: 'im-down', cat: 'daily', sit: '약속·계획', tone: 'casual', pattern: "I'm down for ___.", key: "i'm down",
    ko: '~ 좋아, 콜', when: '제안에 흔쾌히 동의할 때. 20~30대가 많이 써요',
    tip: '"I\'m feeling down"(우울해)과 뜻이 정반대예요. 회사에서는 쓰지 마세요.',
    variants: [
      { en: "I'm down for that.", ko: '그거 좋아.',
        link: { text: "I'm down for that.", sound: 'aim DOWN fər THAT', rules: ['weak'] } },
      { en: "I'm down for tacos.", ko: '타코 콜.',
        link: { text: "I'm down for tacos.", sound: 'aim DOWN fər TA-kohz', rules: ['weak'] } },
      { en: "I'm down to hang out tonight.", ko: '오늘 밤 놀 수 있어.',
        link: { text: "I'm down to hang‿ou(t) tonight.", sound: 'aim DOWN tə HANG-OU(t) tə-NIGHT', rules: ['weak', 'link', 'same'] } }],
    roleplay: { tutor: 'Wanna grab some drinks after work?', ko: '퇴근하고 한잔할래?', answer: "I'm down for that!" } },
  { id: 'how-was-your', cat: 'daily', sit: '스몰토크·근황', tone: 'casual', pattern: 'How was your ___?', key: 'how was your',
    ko: '~ 어땠어?', when: '스몰토크를 시작할 때',
    variants: [
      { en: 'How was your weekend?', ko: '주말 어땠어?',
        link: { text: 'How was your weekend?', sound: 'hau wəz yər WEEK-end', rules: ['weak'] } },
      { en: 'How was your trip?', ko: '여행 어땠어?',
        link: { text: 'How was your trip?', sound: 'hau wəz yər TRIP', rules: ['weak'] } },
      { en: 'How was your day?', ko: '오늘 하루 어땠어?',
        link: { text: 'How was your day?', sound: 'hau wəz yər DAY', rules: ['weak'] } }],
    roleplay: { tutor: 'Hey, I just got back from Hawaii!', ko: '나 하와이 갔다가 방금 왔어!', answer: 'No way! How was your trip?' } },
  { id: 'ive-been-lately', cat: 'daily', sit: '스몰토크·근황', tone: 'casual', pattern: "I've been ___ lately.", key: "i've been",
    ko: '요즘 ~하고 있어', when: '근황을 말할 때',
    variants: [
      { en: "I've been really busy lately.", ko: '요즘 정말 바빴어.',
        link: { text: "I've been really busy lately.", sound: 'aiv bin RI-lee BI-zee LAYT-lee', rules: ['weak'] } },
      { en: "I've been working out a lot lately.", ko: '요즘 운동 많이 하고 있어.',
        link: { text: "I've been working‿out‿a lot lately.", sound: 'aiv bin WER-king-ou-də LOT LAYT-lee', rules: ['weak', 'link', 'flap'] } },
      { en: "I've been into cooking lately.", ko: '요즘 요리에 빠졌어.',
        link: { text: "I've been‿into cooking lately.", sound: 'aiv bi-NIN-too KOO-king LAYT-lee', rules: ['weak', 'link'] } }],
    roleplay: { tutor: "Long time no see! What's new with you?", ko: '오랜만이야! 요즘 어떻게 지내?', answer: "I've been really busy with work lately." } },
  { id: 'not-really-into', cat: 'daily', sit: '감정·의견', tone: 'casual', pattern: "I'm not really into ___.", key: 'not really into',
    ko: '~는 별로 안 좋아해', when: '취향을 부드럽게 거절할 때',
    tip: '"I don\'t like ___"보다 부드럽게 들려요.',
    variants: [
      { en: "I'm not really into horror movies.", ko: '공포 영화는 별로야.',
        link: { text: "I'm no(t) really‿into horror movies.", sound: 'aim na(t) RI-lee-YIN-too HOR-ər MOO-veez', rules: ['stop', 'glide'] } },
      { en: "I'm not really into sports.", ko: '스포츠는 별로 안 좋아해.',
        link: { text: "I'm no(t) really‿into sports.", sound: 'aim na(t) RI-lee-YIN-too SPORTS', rules: ['stop', 'glide'] } },
      { en: "I'm not really into spicy food.", ko: '매운 음식은 별로야.',
        link: { text: "I'm no(t) really‿into spicy food.", sound: 'aim na(t) RI-lee-YIN-too SPAI-see FOOD', rules: ['stop', 'glide'] } }],
    roleplay: { tutor: 'Do you wanna watch a horror movie tonight?', ko: '오늘 밤에 공포 영화 볼래?', answer: "Hmm, I'm not really into horror movies." } },
  { id: 'that-sounds', cat: 'daily', sit: '리액션·맞장구', tone: 'casual', pattern: 'That sounds ___.', key: 'that sounds',
    ko: '그거 ~하겠다', when: '상대 말에 리액션할 때. 회화에서 가장 자주 쓰는 편',
    tip: '명사 앞에는 like를 붙여요. (That sounds like a plan.)',
    variants: [
      { en: 'That sounds fun.', ko: '재밌겠다.',
        link: { text: 'Tha(t) sounds fun.', sound: 'tha(t) SOUNDZ FUN', rules: ['stop'] } },
      { en: 'That sounds rough.', ko: '힘들었겠다.',
        link: { text: 'Tha(t) sounds rough.', sound: 'tha(t) SOUNDZ RUF', rules: ['stop'] } },
      { en: 'That sounds like a plan.', ko: '좋아, 그렇게 하자.',
        link: { text: 'Tha(t) sounds like‿a plan.', sound: 'tha(t) SOUNDZ LAI-kə PLAN', rules: ['stop', 'link', 'weak'] } }],
    roleplay: { tutor: 'I had to work until midnight yesterday.', ko: '어제 자정까지 일했어.', answer: 'Oh no, that sounds rough.' } },
  { id: 'i-feel-like', cat: 'daily', sit: '감정·의견', tone: 'casual', pattern: 'I feel like ___.', key: 'i feel like',
    ko: '~가 당겨 / ~인 것 같아', when: '먹고 싶은 것, 몸 상태, 예감을 말할 때',
    tip: '뒤에 명사가 오면 "~가 당긴다"는 뜻이에요.',
    variants: [
      { en: 'I feel like pizza tonight.', ko: '오늘 밤은 피자가 당겨.',
        link: { text: 'I feel like pizza tonight.', sound: 'ai FEEL laik PEET-sə tə-NIGHT', rules: [] } },
      { en: "I feel like I'm getting sick.", ko: '감기 걸리려나 봐.',
        link: { text: "I feel like‿I'm getting sick.", sound: 'ai FEEL lai-kaim GE-ding SICK', rules: ['link', 'flap'] } },
      { en: "I feel like it's gonna rain.", ko: '비 올 것 같아.',
        link: { text: "I feel like‿it's gonna rain.", sound: 'ai FEEL lai-kits GUH-nə RAIN', rules: ['link', 'weak'] } }],
    roleplay: { tutor: 'What do you wanna eat tonight?', ko: '오늘 저녁 뭐 먹고 싶어?', answer: 'I feel like Korean food.' } },
  { id: 'ill-have', cat: 'daily', sit: '카페·식당', tone: 'neutral', pattern: "I'll have ___.", key: "i'll have",
    ko: '~로 할게요', when: '메뉴를 고르고 주문을 확정할 때',
    variants: [
      { en: "I'll have the same.", ko: '저도 같은 걸로 할게요.',
        link: { text: "I'll‿have the same.", sound: 'ai-ləv thə SAME', rules: ['weak', 'link'] } },
      { en: "I'll have the chicken salad.", ko: '치킨 샐러드로 할게요.',
        link: { text: "I'll‿have the chicken salad.", sound: 'ai-ləv thə CHI-kən SA-ləd', rules: ['weak', 'link'] } },
      { en: "I'll have a medium latte with oat milk.", ko: '미디엄 라테에 귀리 우유로 할게요.',
        link: { text: "I'll‿have‿a medium latte with‿oat milk.", sound: 'ai-lə-və MEE-dee-əm LA-dei wi-thoat MILK', rules: ['weak', 'link', 'flap'] } }],
    roleplay: { tutor: 'Are you ready to order?', ko: '주문하시겠어요?', answer: "Yes, I'll have the chicken salad, please." } },
  { id: 'can-we-sit', cat: 'daily', sit: '카페·식당', tone: 'neutral', pattern: 'Can we sit ___?', key: 'can we sit',
    ko: '~에 앉아도 될까요?', when: '식당에서 자리를 고를 때',
    variants: [
      { en: 'Can we sit outside?', ko: '밖에 앉아도 될까요?',
        link: { text: 'Can we sit‿outside?', sound: 'kən wee si-dout-SIDE', rules: ['weak', 'link', 'flap'] } },
      { en: 'Can we sit by the window?', ko: '창가에 앉아도 될까요?',
        link: { text: 'Can we si(t) by the window?', sound: 'kən wee SI(t) bai thə WIN-dou', rules: ['weak', 'stop'] } },
      { en: 'Can we sit at the bar?', ko: '바 자리에 앉아도 될까요?',
        link: { text: 'Can we sit‿a(t) the bar?', sound: 'kən wee si-də(t) thə BAR', rules: ['weak', 'flap', 'stop'] } }],
    roleplay: { tutor: 'Hi, how many?', ko: '안녕하세요, 몇 분이세요?', answer: 'Two. Can we sit by the window?' } },
  { id: 'looking-for', cat: 'daily', sit: '쇼핑', tone: 'neutral', pattern: "I'm looking for ___.", key: "i'm looking for",
    ko: '~를 찾고 있어요', when: '매장에서 찾는 물건을 말할 때',
    tip: '그냥 둘러볼 때는 "I\'m just looking, thanks."라고 하면 돼요.',
    variants: [
      { en: "I'm looking for a gift for my mom.", ko: '엄마 선물을 찾고 있어요.',
        link: { text: "I'm looking for‿a gift for my mom.", sound: 'aim LOO-king fə-rə GIFT fər mai MOM', rules: ['weak', 'link'] } },
      { en: "I'm looking for a charger for this phone.", ko: '이 폰에 맞는 충전기를 찾고 있어요.',
        link: { text: "I'm looking for‿a charger for this phone.", sound: 'aim LOO-king fə-rə CHAR-jər fər this PHONE', rules: ['weak', 'link'] } },
      { en: "I'm looking for something a little cheaper.", ko: '조금 더 싼 걸 찾고 있어요.',
        link: { text: "I'm looking for something‿a little cheaper.", sound: 'aim LOO-king fər SUM-thing-ə LI-dəl CHEE-pər', rules: ['weak', 'link', 'flap'] } }],
    roleplay: { tutor: 'Hi! Can I help you find anything?', ko: '찾으시는 거 도와드릴까요?', answer: "Yes, I'm looking for a gift for my mom." } },
  { id: 'try-on', cat: 'daily', sit: '쇼핑', tone: 'neutral', pattern: 'Can I try ___ on?', key: 'can i try',
    ko: '~ 입어 봐도 돼요?', when: '옷이나 신발을 입어 보거나 신어 보고 싶을 때',
    tip: 'this, it, them은 try와 on 사이에 넣어요. "try on this"는 어색해요.',
    variants: [
      { en: 'Can I try this on?', ko: '이거 입어 봐도 돼요?',
        link: { text: 'Can‿I try this‿on?', sound: 'kə-nai TRAI thi-SON', rules: ['link', 'weak'] } },
      { en: 'Can I try these on in a smaller size?', ko: '이거 작은 사이즈로 입어 봐도 돼요?',
        link: { text: 'Can‿I try these‿on‿in‿a smaller size?', sound: 'kə-nai TRAI thee-zo-ni-nə SMA-lər SIZE', rules: ['link', 'weak'] } },
      { en: 'Can I try the other one on?', ko: '다른 거 입어 봐도 돼요?',
        link: { text: 'Can‿I try the‿other‿one‿on?', sound: 'kə-nai TRAI thee-YUH-thər WUH-non', rules: ['link', 'glide'] } }],
    roleplay: { tutor: 'Those jeans are on sale today.', ko: '그 청바지 오늘 세일해요.', answer: 'Oh nice. Can I try them on?' } },
  { id: 'any-plans', cat: 'daily', sit: '스몰토크·근황', tone: 'casual', pattern: 'Any plans for ___?', key: 'any plans',
    ko: '~에 계획 있어?', when: '가볍게 대화를 시작할 때',
    tip: '원래는 "Do you have any plans for ~?"인데, 말할 때는 앞을 빼고 이렇게 많이 써요.',
    variants: [
      { en: 'Any plans for the weekend?', ko: '주말에 계획 있어?',
        link: { text: 'Any plans for the weekend?', sound: 'E-nee PLANZ fər thə WEEK-end', rules: ['weak'] } },
      { en: 'Any plans for tonight?', ko: '오늘 밤에 뭐 해?',
        link: { text: 'Any plans for tonight?', sound: 'E-nee PLANZ fər tə-NIGHT', rules: ['weak'] } },
      { en: 'Any plans for the holidays?', ko: '연휴에 계획 있어?',
        link: { text: 'Any plans for the holidays?', sound: 'E-nee PLANZ fər thə HA-lə-deiz', rules: ['weak'] } }],
    roleplay: { tutor: "Finally, it's Friday!", ko: '드디어 금요일이다!', answer: 'I know! Any plans for the weekend?' } },
  { id: 'you-must-be', cat: 'daily', sit: '리액션·맞장구', tone: 'casual', pattern: 'You must be ___.', key: 'you must be',
    ko: '~하겠다', when: '상대 기분을 짐작해서 공감할 때',
    tip: '여기서 must는 "~해야 한다"가 아니라 "분명 ~일 거다"라는 추측이에요.',
    variants: [
      { en: 'You must be tired.', ko: '피곤하겠다.',
        link: { text: 'You mus(t) be tired.', sound: 'yu MUS(t) bee TIRED', rules: ['stop'] } },
      { en: 'You must be so excited.', ko: '엄청 설레겠다.',
        link: { text: 'You mus(t) be so‿excited.', sound: 'yu mus(t) bee SO-wik-SAI-did', rules: ['stop', 'glide', 'flap'] } },
      { en: 'You must be relieved.', ko: '한시름 놨겠다.',
        link: { text: 'You mus(t) be relieved.', sound: 'yu mus(t) bee ri-LEEVD', rules: ['stop'] } }],
    roleplay: { tutor: 'I just finished a twelve-hour shift.', ko: '방금 12시간 근무 끝났어.', answer: 'Wow, you must be exhausted.' } },
  { id: 'i-bet', cat: 'daily', sit: '리액션·맞장구', tone: 'casual', pattern: 'I bet ___.', key: 'i bet',
    ko: '분명 ~했겠다', when: '상대 이야기에 "그랬겠다"고 맞장구칠 때',
    variants: [
      { en: 'I bet it was amazing.', ko: '진짜 좋았겠다.',
        link: { text: 'I bet‿i(t) was‿amazing.', sound: 'ai BE-di(t) wə-zə-MEI-zing', rules: ['flap', 'stop', 'link', 'weak'] } },
      { en: "I bet you're exhausted.", ko: '엄청 지쳤겠다.',
        link: { text: "I bet‿you're‿exhausted.", sound: 'ai BE-chə-rig-ZAWS-tid', rules: ['yu', 'link'] } },
      { en: 'I bet she was surprised.', ko: '그 사람 놀랐겠다.',
        link: { text: 'I be(t) she was surprised.', sound: 'ai BE(t) shee wəz sər-PRIZED', rules: ['stop', 'weak'] } }],
    roleplay: { tutor: 'I saw the Northern Lights in Iceland!', ko: '아이슬란드에서 오로라 봤어!', answer: 'No way! I bet it was amazing.' } },
  { id: 'not-sure', cat: 'daily', sit: '감정·의견', tone: 'neutral', pattern: "I'm not sure ___.", key: "i'm not sure",
    ko: '~인지 잘 모르겠어', when: '단정하지 않고 조심스럽게 말할 때',
    tip: '"I don\'t know"보다 부드럽고, 반대 의견을 돌려 말할 때도 자주 써요.',
    variants: [
      { en: "I'm not sure that's a good idea.", ko: '그게 좋은 생각인지 잘 모르겠어.',
        link: { text: "I'm no(t) sure that's‿a good‿idea.", sound: 'aim NA(t) SHUR tha-tsə GU-dai-DEE-ə', rules: ['stop', 'link'] } },
      { en: "I'm not sure if I can make it.", ko: '갈 수 있을지 모르겠어.',
        link: { text: "I'm no(t) sure‿if‿I can make‿it.", sound: 'aim na(t) SHU-ri-fai kən MAY-kit', rules: ['stop', 'link', 'weak'] } },
      { en: "I'm not sure what you mean.", ko: '무슨 말인지 잘 모르겠어.',
        link: { text: "I'm no(t) sure what‿you mean.", sound: 'aim na(t) SHUR wə-chə MEAN', rules: ['stop', 'yu'] } }],
    roleplay: { tutor: "Let's drive to the beach tonight!", ko: '오늘 밤에 바다로 드라이브 가자!', answer: "Hmm, I'm not sure that's a good idea. It's pretty late." } },
  { id: 'do-me-a-favor', cat: 'daily', sit: '부탁·거절', tone: 'neutral', pattern: 'Could you do me a favor and ___?', key: 'do me a favor',
    ko: '부탁 하나만, ~해 줄래?', when: '친구나 동료에게 부탁할 때',
    variants: [
      { en: 'Could you do me a favor and grab my charger?', ko: '내 충전기 좀 갖다줄래?',
        link: { text: 'Could you do me‿a favor‿and grab my charger?', sound: 'ku-jə DOO mee-ə FEI-vər-ən GRAB mai CHAR-jər', rules: ['yu', 'glide', 'weak', 'link'] } },
      { en: 'Could you do me a favor and watch my bag for a sec?', ko: '잠깐 내 가방 좀 봐줄래?',
        link: { text: 'Could you do me‿a favor‿and watch my bag for‿a sec?', sound: 'ku-jə DOO mee-ə FEI-vər-ən WATCH mai BAG fə-rə SEC', rules: ['yu', 'glide', 'weak', 'link'] } },
      { en: 'Could you do me a favor and text me when you get there?', ko: '도착하면 문자 좀 해줄래?',
        link: { text: 'Could you do me‿a favor‿and tex(t) me when you ge(t) there?', sound: 'ku-jə DOO mee-ə FEI-vər-ən TEKS mee wen yu ge(t) THERE', rules: ['yu', 'glide', 'weak', 'stop'] } }],
    roleplay: { tutor: "I'm heading to the store. Need anything?", ko: '나 가게 가는데, 필요한 거 있어?', answer: 'Yeah, could you do me a favor and grab some milk?' } },
  { id: 'do-you-mind-if', cat: 'daily', sit: '부탁·거절', tone: 'neutral', pattern: 'Do you mind if I ___?', key: 'do you mind if',
    ko: '~해도 될까요?', when: '허락을 구할 때',
    tip: '"No"라고 답해야 "괜찮아요(신경 안 써요)"라는 뜻이에요. "Yes"는 "싫어요"가 돼요. 보통 "Not at all"이나 "Go ahead"라고 답해요.',
    variants: [
      { en: 'Do you mind if I open the window?', ko: '창문 좀 열어도 될까요?',
        link: { text: 'Do you mind‿if‿I‿open the window?', sound: 'də-yə MIN-di-fai-YOU-pən thə WIN-dou', rules: ['weak', 'link', 'glide'] } },
      { en: 'Do you mind if I join you?', ko: '같이 껴도 될까요?',
        link: { text: 'Do you mind‿if‿I join you?', sound: 'də-yə MIN-di-fai JOIN yu', rules: ['weak', 'link'] } },
      { en: 'Do you mind if I bring a friend?', ko: '친구 한 명 데려가도 될까?',
        link: { text: 'Do you mind‿if‿I bring‿a friend?', sound: 'də-yə MIN-di-fai BRING-ə FREND', rules: ['weak', 'link'] } }],
    roleplay: { tutor: 'Come on in! Make yourself at home.', ko: '들어와! 편하게 있어.', answer: 'Thanks! Do you mind if I open the window?' } },
  { id: 'love-to-but', cat: 'daily', sit: '부탁·거절', tone: 'casual', pattern: "I'd love to, but ___.", key: "i'd love to",
    ko: '정말 그러고 싶은데, ~', when: '초대나 제안을 부드럽게 거절할 때',
    tip: '거절 뒤에 "Maybe next time?"을 붙이면 더 자연스러워요.',
    variants: [
      { en: "I'd love to, but I already have plans.", ko: '가고 싶은데 이미 약속이 있어.',
        link: { text: "I'd love to, but‿I‿already have plans.", sound: 'aid LUV tə, bə-dai-yawl-RE-dee hav PLANZ', rules: ['weak', 'flap', 'glide'] } },
      { en: "I'd love to, but I'm swamped this week.", ko: '그러고 싶은데 이번 주엔 일이 너무 많아.',
        link: { text: "I'd love to, but‿I'm swamped this week.", sound: 'aid LUV tə, bə-daim SWAMPT this WEEK', rules: ['weak', 'flap'] } },
      { en: "I'd love to, but I can't tonight.", ko: '그러고 싶은데 오늘 밤은 안 돼.',
        link: { text: "I'd love to, but‿I can'(t) tonight.", sound: 'aid LUV tə, bə-dai KAN(t) tə-NIGHT', rules: ['weak', 'flap', 'stop'] } }],
    roleplay: { tutor: "We're going bowling tonight. Wanna come?", ko: '오늘 밤에 볼링 치러 가는데, 올래?', answer: "I'd love to, but I already have plans. Maybe next time?" } },
);
