CARDS.push(
  { id: 'just-to-clarify', cat: 'office', sit: '되묻기·확인', tone: 'neutral', pattern: 'Just to clarify, ___?', key: 'just to clarify',
    ko: '확인차 여쭤보면, ~?', when: '지시나 내용을 다시 확인할 때',
    tip: '못 알아들었을 때 "Sorry?"만 반복하는 것보다 훨씬 프로답게 들려요.',
    variants: [
      { en: 'Just to clarify, the deadline is Friday?', ko: '확인차 여쭤보면, 마감이 금요일이죠?' },
      { en: 'Just to clarify, you want me to send it to the client?', ko: '확인하자면, 이걸 클라이언트에게 보내라는 거죠?' },
      { en: 'Just to clarify, are we meeting in person?', ko: '확인하자면, 대면으로 만나는 거죠?' }],
    roleplay: { tutor: 'Can you send the report to Jake by Friday?', ko: '금요일까지 보고서 Jake한테 보내줄래요?', answer: 'Sure. Just to clarify, the final version or the draft?' } },
  { id: 'i-was-wondering-if', cat: 'office', sit: '업무 요청', tone: 'polite', pattern: 'I was wondering if ___.', key: 'i was wondering if',
    ko: '혹시 ~해도 될까요', when: '부탁하기 어려운 것을 공손하게 요청할 때',
    variants: [
      { en: 'I was wondering if you could take a look at this.', ko: '혹시 이것 좀 봐주실 수 있을까요?' },
      { en: 'I was wondering if I could leave early today.', ko: '혹시 오늘 일찍 퇴근해도 될까요?' },
      { en: 'I was wondering if we could push the meeting.', ko: '혹시 회의를 미룰 수 있을까요?' }],
    roleplay: { tutor: "Hey, what's up?", ko: '무슨 일이에요?', answer: 'I was wondering if you could take a look at my slides.' } },
  { id: 'get-back-to-you', cat: 'office', sit: '진행 보고', tone: 'neutral', pattern: "I'll get back to you ___.", key: 'get back to you',
    ko: '~ 다시 알려드릴게요', when: '당장 답하지 못할 때',
    variants: [
      { en: "I'll get back to you on that.", ko: '그건 확인하고 다시 알려드릴게요.',
        link: { text: "I'll ge(t) back to you‿on that.", sound: 'ail ge(t) BACK tə yu-wan THAT', rules: ['stop', 'weak', 'glide'] } },
      { en: "I'll get back to you by end of day.", ko: '오늘 퇴근 전까지 알려드릴게요.',
        link: { text: "I'll ge(t) back to you by‿end‿of day.", sound: 'ail ge(t) BACK tə yu bai-YEN-də DAY', rules: ['stop', 'weak', 'glide', 'link'] } },
      { en: "I'll get back to you once I hear from them.", ko: '그쪽에서 연락 오면 바로 알려드릴게요.',
        link: { text: "I'll ge(t) back to you once‿I hear from them.", sound: 'ail ge(t) BACK tə yu WAN-sai HEER frəm thəm', rules: ['stop', 'weak', 'link'] } }],
    roleplay: { tutor: 'Do you know when the client will sign?', ko: '클라이언트가 언제 서명할지 알아요?', answer: "Not yet. I'll get back to you once I hear from them." } },
  { id: 'see-your-point', cat: 'office', sit: '동의·반대', tone: 'neutral', pattern: 'I see your point, but ___.', key: 'i see your point',
    ko: '무슨 말인지 알겠는데, ~', when: '회의에서 반대 의견을 낼 때',
    variants: [
      { en: "I see your point, but I'm worried about the timeline.", ko: '무슨 말인지 알겠는데, 일정이 걱정돼요.' },
      { en: 'I see your point, but I think we need more data.', ko: '말씀은 이해하는데, 데이터가 더 필요할 것 같아요.' },
      { en: 'I see your point, but the client might not like it.', ko: '무슨 뜻인지 알겠는데, 클라이언트가 안 좋아할 수도 있어요.' }],
    roleplay: { tutor: 'I think we should launch next week.', ko: '다음 주에 출시하는 게 좋겠어요.', answer: "I see your point, but I'm worried about the timeline." } },
  { id: 'quick-question', cat: 'office', sit: '업무 요청', tone: 'casual', pattern: 'Quick question about ___.', key: 'quick question',
    ko: '~ 관련해서 잠깐 질문', when: '동료에게 가볍게 물어볼 때',
    variants: [
      { en: 'Quick question about the report.', ko: '보고서 관련해서 잠깐 질문이요.' },
      { en: 'Quick question, are we still meeting at 2?', ko: '잠깐만요, 우리 2시 회의 그대로죠?' },
      { en: 'Quick question about the new schedule.', ko: '새 일정 관련해서 잠깐 질문이요.' }],
    roleplay: { tutor: 'Hi! Did you need something?', ko: '뭐 필요한 거 있어요?', answer: 'Yeah, quick question about the report.' } },
  { id: 'hows-going', cat: 'office', sit: '동료 스몰토크', tone: 'casual', pattern: "How's ___ going?", key: ["how's", 'how is'],
    ko: '~ 잘 돼가?', when: '동료에게 가볍게 안부를 물을 때',
    variants: [
      { en: "How's the project going?", ko: '프로젝트 잘 돼가?',
        link: { text: "How's the project going?", sound: 'HOWZ thə PRA-jekt GO-ing', rules: ['weak'] } },
      { en: "How's your week going?", ko: '이번 주 어때?',
        link: { text: "How's your week going?", sound: 'HOWZ yər WEEK GO-ing', rules: ['weak'] } },
      { en: "How's the new job going?", ko: '새 일은 할 만해?',
        link: { text: "How's the new job going?", sound: 'HOWZ thə NEW JOB GO-ing', rules: ['weak'] } }],
    roleplay: { tutor: 'Hey! Long day?', ko: '안녕! 오늘 힘들었어?', answer: "Kind of. How's the project going on your side?" } },
  { id: 'are-you-going-to', cat: 'office', sit: '동료 스몰토크', tone: 'casual', pattern: 'Are you going to ___?', key: 'are you going to',
    ko: '~에 갈 거야?', when: '회식이나 사내 행사에 가는지 물을 때',
    tip: '말할 때는 "Are you gonna ~?"처럼 줄여서 많이 말해요.',
    variants: [
      { en: 'Are you going to the team lunch?', ko: '팀 점심 갈 거야?',
        link: { text: 'Are you going to the team lunch?', sound: 'ar-yə GO-ing tə thə TEEM LUNCH', rules: ['weak'] } },
      { en: 'Are you going to the holiday party?', ko: '연말 파티 갈 거야?',
        link: { text: 'Are you going to the holiday party?', sound: 'ar-yə GO-ing tə thə HA-lə-day PAR-dee', rules: ['weak', 'flap'] } },
      { en: "Are you going to Sarah's farewell?", ko: '세라 송별회 갈 거야?',
        link: { text: "Are you going to Sarah's farewell?", sound: 'ar-yə GO-ing tə SE-rəz fair-WELL', rules: ['weak'] } }],
    roleplay: { tutor: "I just got the invite for Friday's team dinner.", ko: '금요일 팀 저녁 초대 방금 받았어.', answer: 'Me too. Are you going to the team dinner?' } },
  { id: 'i-heard', cat: 'office', sit: '동료 스몰토크', tone: 'casual', pattern: 'I heard ___.', key: 'i heard',
    ko: '~라며?', when: '들은 소식으로 대화를 시작할 때',
    variants: [
      { en: 'I heard you got promoted!', ko: '승진했다며!',
        link: { text: 'I heard you go(t) promoted!', sound: 'ai HER-jə GA(t) prə-MOH-did', rules: ['yu', 'stop', 'flap'] } },
      { en: "I heard you're moving to the Seoul office.", ko: '서울 사무실로 옮긴다며.',
        link: { text: "I heard you're moving to the Seoul‿office.", sound: 'ai HER-jər MOO-ving tə thə SOH-LAW-fis', rules: ['yu', 'weak', 'link'] } },
      { en: 'I heard the new café downstairs is good.', ko: '아래층 새 카페 괜찮다며.',
        link: { text: 'I heard the new café downstairs‿is good.', sound: 'ai HERD thə NEW ka-FAY down-STAIR-zəz GOOD', rules: ['link', 'weak'] } }],
    roleplay: { tutor: "Morning! What's new?", ko: '좋은 아침! 별일 없어?', answer: 'Not much. Oh, I heard you got promoted! Congrats!' } },
  { id: 'we-should', cat: 'office', sit: '의견 말하기', tone: 'neutral', pattern: 'I think we should ___.', key: 'i think we should',
    ko: '~하는 게 좋겠어요', when: '회의에서 의견을 낼 때',
    variants: [
      { en: 'I think we should push the launch.', ko: '출시를 미루는 게 좋겠어요.',
        link: { text: 'I think we should push the launch.', sound: 'ai THINK wee shəd PUSH thə LAWNCH', rules: ['weak'] } },
      { en: 'I think we should ask the client first.', ko: '클라이언트에게 먼저 물어보는 게 좋겠어요.',
        link: { text: 'I think we should‿ask the client first.', sound: 'ai THINK wee shə-DASK thə KLAI-ənt FIRST', rules: ['weak', 'link'] } },
      { en: 'I think we should keep it simple.', ko: '단순하게 가는 게 좋겠어요.',
        link: { text: 'I think we should keep‿it simple.', sound: 'ai THINK wee shəd KEE-pit SIM-pəl', rules: ['weak', 'link'] } }],
    roleplay: { tutor: 'The client wants more features, but we only have two weeks.', ko: '클라이언트는 기능을 더 원하는데 2주밖에 없어요.', answer: 'I think we should keep it simple for now.' } },
  { id: 'what-if-we', cat: 'office', sit: '의견 말하기', tone: 'neutral', pattern: 'What if we ___?', key: 'what if we',
    ko: '~하면 어때요?', when: '다른 방법을 제안할 때',
    tip: '"How about ~?"보다 아이디어를 던져 보는 느낌이 강해요.',
    variants: [
      { en: 'What if we split the task?', ko: '일을 나눠서 하면 어때요?',
        link: { text: 'What‿if we split the task?', sound: 'wə-DIF wee SPLIT thə TASK', rules: ['flap', 'link'] } },
      { en: 'What if we move the deadline?', ko: '마감을 옮기면 어때요?',
        link: { text: 'What‿if we move the deadline?', sound: 'wə-DIF wee MOOV thə DED-line', rules: ['flap', 'link'] } },
      { en: 'What if we try a different approach?', ko: '다른 방법을 써 보면 어때요?',
        link: { text: 'What‿if we try‿a different‿approach?', sound: 'wə-DIF wee TRAI-yə DIF-rən-tə-PROHCH', rules: ['flap', 'glide', 'link'] } }],
    roleplay: { tutor: "We're behind schedule again. Any ideas?", ko: '또 일정이 밀렸어요. 좋은 생각 있어요?', answer: 'What if we split the task between the two of us?' } },
  { id: 'might-be-better', cat: 'office', sit: '의견 말하기', tone: 'polite', pattern: 'It might be better to ___.', key: 'it might be better',
    ko: '~하는 게 나을 수도 있어요', when: '다른 의견을 부드럽게 제안할 때',
    variants: [
      { en: 'It might be better to wait until Monday.', ko: '월요일까지 기다리는 게 나을 수도 있어요.',
        link: { text: 'I(t) migh(t) be better to wait‿until Monday.', sound: 'i(t) MAI(t) bee BE-dər tə WAY-dən-til MUN-day', rules: ['stop', 'flap', 'link', 'weak'] } },
      { en: 'It might be better to call them.', ko: '그쪽에 전화하는 게 나을 수도 있어요.',
        link: { text: 'I(t) migh(t) be better to call them.', sound: 'i(t) MAI(t) bee BE-dər tə CALL əm', rules: ['stop', 'flap', 'weak'] } },
      { en: 'It might be better to start small.', ko: '작게 시작하는 게 나을 수도 있어요.',
        link: { text: 'I(t) migh(t) be better to star(t) small.', sound: 'i(t) MAI(t) bee BE-dər tə STAR(t) SMALL', rules: ['stop', 'flap', 'weak'] } }],
    roleplay: { tutor: 'Should I email the client about the delay right now?', ko: '지연 건으로 지금 바로 클라이언트에게 메일 보낼까요?', answer: 'It might be better to call them instead.' } },
  { id: 'i-agree-with', cat: 'office', sit: '동의·반대', tone: 'neutral', pattern: 'I agree with ___.', key: 'i agree with',
    ko: '~에 동의해요', when: '회의에서 누군가의 의견에 동의할 때',
    tip: '"I\'m agree"는 틀린 표현이에요. agree는 동사라서 "I agree"라고 해요.',
    variants: [
      { en: 'I agree with Jake.', ko: 'Jake 의견에 동의해요.',
        link: { text: 'I‿agree with Jake.', sound: 'ai-yə-GREE with JAKE', rules: ['glide'] } },
      { en: 'I agree with you on that.', ko: '그 부분은 저도 같은 생각이에요.',
        link: { text: 'I‿agree with you‿on that.', sound: 'ai-yə-GREE with yu-wan THAT', rules: ['glide'] } },
      { en: 'I agree with the first option.', ko: '첫 번째 안에 동의해요.',
        link: { text: 'I‿agree with the first‿option.', sound: 'ai-yə-GREE with thə FIR-STAP-shən', rules: ['glide', 'link'] } }],
    roleplay: { tutor: "I think we should go with the first option. It's cheaper.", ko: '첫 번째 안으로 가는 게 좋겠어요. 더 싸니까요.', answer: 'I agree with you on that.' } },
  { id: 'not-sure-agree', cat: 'office', sit: '동의·반대', tone: 'polite', pattern: "I'm not sure I agree with ___.", key: "i'm not sure i agree",
    ko: '~에는 동의하기 어려울 것 같아요', when: '반대 의견을 정중하게 낼 때',
    tip: '반대할 때는 이유를 바로 붙이면 설득력이 생겨요. (…, because ~)',
    variants: [
      { en: "I'm not sure I agree with that.", ko: '그건 동의하기 어려울 것 같아요.',
        link: { text: "I'm no(t) sure‿I‿agree with that.", sound: 'aim NA(t) SHUR-ai-yə-GREE with THAT', rules: ['stop', 'link', 'glide'] } },
      { en: "I'm not sure I agree with the timeline.", ko: '그 일정에는 동의하기 어려울 것 같아요.',
        link: { text: "I'm no(t) sure‿I‿agree with the timeline.", sound: 'aim NA(t) SHUR-ai-yə-GREE with thə TIME-line', rules: ['stop', 'link', 'glide'] } },
      { en: "I'm not sure I agree with cutting the budget.", ko: '예산을 줄이는 건 동의하기 어려울 것 같아요.',
        link: { text: "I'm no(t) sure‿I‿agree with cutting the budget.", sound: 'aim NA(t) SHUR-ai-yə-GREE with KUH-ding thə BUH-jit', rules: ['stop', 'link', 'glide', 'flap'] } }],
    roleplay: { tutor: "Let's cut the testing phase to save time.", ko: '시간 아끼게 테스트 단계를 줄입시다.', answer: "I'm not sure I agree with that. We might miss some bugs." } },
  { id: 'say-again', cat: 'office', sit: '되묻기·확인', tone: 'neutral', pattern: 'Could you say ___ again?', key: 'could you say',
    ko: '~ 다시 말씀해 주시겠어요?', when: '못 알아들은 부분을 다시 들어야 할 때',
    tip: '모르는 채로 넘어가는 것보다 한 번 묻는 게 훨씬 프로다워요. 원어민끼리도 자주 해요.',
    variants: [
      { en: 'Could you say that again?', ko: '다시 한번 말씀해 주시겠어요?',
        link: { text: 'Could you say that‿again?', sound: 'ku-jə SAY tha-də-GEN', rules: ['yu', 'flap', 'link'] } },
      { en: 'Could you say the last part again?', ko: '마지막 부분 다시 말씀해 주시겠어요?',
        link: { text: 'Could you say the las(t) part‿again?', sound: 'ku-jə SAY thə LAS(t) PAR-də-GEN', rules: ['yu', 'stop', 'flap', 'link'] } },
      { en: 'Could you say the number again?', ko: '그 숫자 다시 말씀해 주시겠어요?',
        link: { text: 'Could you say the number‿again?', sound: 'ku-jə SAY thə NUM-bə-rə-GEN', rules: ['yu', 'link'] } }],
    roleplay: { tutor: 'Okay, the code is 4-7-9-2-8-1. Got it?', ko: '자, 코드는 479281이에요. 적었어요?', answer: 'Sorry, could you say the number again?' } },
  { id: 'so-youre-saying', cat: 'office', sit: '되묻기·확인', tone: 'neutral', pattern: "So you're saying ___?", key: "so you're saying",
    ko: '그러니까 ~라는 말씀이죠?', when: '상대 말을 내 말로 정리해서 확인할 때',
    variants: [
      { en: "So you're saying we need more time?", ko: '그러니까 시간이 더 필요하다는 거죠?',
        link: { text: "So you're saying we need more time?", sound: 'so yər SAY-ing wee NEED MORE TIME', rules: ['weak'] } },
      { en: "So you're saying the client said no?", ko: '그러니까 클라이언트가 거절했다는 거죠?',
        link: { text: "So you're saying the client said no?", sound: 'so yər SAY-ing thə KLAI-ənt SED NO', rules: ['weak'] } },
      { en: "So you're saying I should redo it?", ko: '그러니까 제가 다시 해야 한다는 거죠?',
        link: { text: "So you're saying‿I should redo‿it?", sound: 'so yər SAY-ing-ai shəd ree-DOO-wit', rules: ['weak', 'link', 'glide'] } }],
    roleplay: { tutor: "Honestly, I don't think we can finish by Friday.", ko: '솔직히 금요일까지는 못 끝낼 것 같아요.', answer: "So you're saying we need more time?" } },
  { id: 'send-me', cat: 'office', sit: '업무 요청', tone: 'neutral', pattern: 'Could you send me ___?', key: 'could you send me',
    ko: '~ 보내 주실 수 있어요?', when: '파일이나 자료를 요청할 때',
    variants: [
      { en: 'Could you send me the file?', ko: '파일 좀 보내 주실 수 있어요?',
        link: { text: 'Could you send me the file?', sound: 'ku-jə SEN mee thə FILE', rules: ['yu', 'weak'] } },
      { en: 'Could you send me the latest version?', ko: '최신 버전 좀 보내 주실 수 있어요?',
        link: { text: 'Could you send me the lates(t) version?', sound: 'ku-jə SEN mee thə LAY-dis(t) VER-zhən', rules: ['yu', 'stop', 'flap'] } },
      { en: 'Could you send me the meeting notes?', ko: '회의록 좀 보내 주실 수 있어요?',
        link: { text: 'Could you send me the meeting notes?', sound: 'ku-jə SEN mee thə MEE-ding NOHTS', rules: ['yu', 'flap'] } }],
    roleplay: { tutor: 'I updated the presentation last night.', ko: '어젯밤에 발표 자료 업데이트했어요.', answer: 'Great. Could you send me the latest version?' } },
  { id: 'still-working-on', cat: 'office', sit: '진행 보고', tone: 'neutral', pattern: "I'm still working on ___.", key: "i'm still working on",
    ko: '아직 ~ 하고 있어요', when: '진행 상황을 물어볼 때 답할 때',
    variants: [
      { en: "I'm still working on the report.", ko: '보고서 아직 작업 중이에요.',
        link: { text: "I'm still working‿on the report.", sound: 'aim STILL WER-king-on thə ri-PORT', rules: ['link'] } },
      { en: "I'm still working on the slides.", ko: '슬라이드 아직 작업 중이에요.',
        link: { text: "I'm still working‿on the slides.", sound: 'aim STILL WER-king-on thə SLIDEZ', rules: ['link'] } },
      { en: "I'm still working on it, but it's almost done.", ko: '아직 하고 있는데 거의 다 됐어요.',
        link: { text: "I'm still working‿on‿it, but‿it's‿almost done.", sound: 'aim STILL WER-king-o-nit, bə-dit-SAWL-mohst DUN', rules: ['link', 'flap'] } }],
    roleplay: { tutor: "How's the report coming along?", ko: '보고서는 어떻게 돼가요?', answer: "I'm still working on it, but it's almost done." } },
  { id: 'heads-up', cat: 'office', sit: '진행 보고', tone: 'neutral', pattern: 'Just a heads-up, ___.', key: 'heads up',
    ko: '미리 말씀드리면, ~', when: '미리 알려둘 일이 있을 때',
    tip: '외국계 회사 메신저와 메일에서 정말 자주 봐요. "FYI"와 비슷하지만 더 부드러워요.',
    variants: [
      { en: "Just a heads-up, I'll be out tomorrow.", ko: '미리 말씀드리면, 저 내일 자리에 없어요.',
        link: { text: "Just‿a heads-up, I'll be‿out tomorrow.", sound: 'jəs-tə HEDZ-up, ail bee-YOUT tə-MA-roh', rules: ['link', 'glide'] } },
      { en: 'Just a heads-up, the client moved the meeting.', ko: '미리 말씀드리면, 클라이언트가 회의 시간을 옮겼어요.',
        link: { text: 'Just‿a heads-up, the client moved the meeting.', sound: 'jəs-tə HEDZ-up, thə KLAI-ənt MOOVD thə MEE-ding', rules: ['link', 'flap'] } },
      { en: 'Just a heads-up, the file is pretty big.', ko: '미리 말씀드리면, 파일이 꽤 커요.',
        link: { text: 'Just‿a heads-up, the file‿is pretty big.', sound: 'jəs-tə HEDZ-up, thə FAI-liz PRI-dee BIG', rules: ['link', 'flap'] } }],
    roleplay: { tutor: 'Anything I should know before the meeting?', ko: '회의 전에 알아둬야 할 거 있어요?', answer: 'Just a heads-up, the client moved the meeting to 3.' } },
  { id: 'work-for-you', cat: 'office', sit: '일정 조율', tone: 'neutral', pattern: 'Does ___ work for you?', key: 'work for you',
    ko: '~ 괜찮으세요?', when: '회의 시간을 제안할 때',
    variants: [
      { en: 'Does 3 p.m. work for you?', ko: '오후 3시 괜찮으세요?',
        link: { text: 'Does 3 p.m. work for you?', sound: 'dəz THREE pee-EM WERK fər yu', rules: ['weak'] } },
      { en: 'Does Thursday work for you?', ko: '목요일 괜찮으세요?',
        link: { text: 'Does Thursday work for you?', sound: 'dəz THURZ-day WERK fər yu', rules: ['weak'] } },
      { en: 'Does next week work for you?', ko: '다음 주 괜찮으세요?',
        link: { text: 'Does nex(t) week work for you?', sound: 'dəz NEKS WEEK WERK fər yu', rules: ['weak', 'stop'] } }],
    roleplay: { tutor: 'We need to talk about the budget sometime this week.', ko: '이번 주 중에 예산 얘기 좀 해야 해요.', answer: 'Sure. Does Thursday work for you?' } },
  { id: 'can-we-move', cat: 'office', sit: '일정 조율', tone: 'neutral', pattern: 'Can we move ___?', key: 'can we move',
    ko: '~ 옮길 수 있을까요?', when: '일정을 바꾸고 싶을 때',
    tip: '"move it up"은 앞당기기, "push it back"은 뒤로 미루기예요.',
    variants: [
      { en: 'Can we move the meeting to Friday?', ko: '회의를 금요일로 옮길 수 있을까요?',
        link: { text: 'Can we move the meeting to Friday?', sound: 'kən wee MOOV thə MEE-ding tə FRAI-day', rules: ['weak', 'flap'] } },
      { en: 'Can we move our call to 4?', ko: '통화를 4시로 옮길 수 있을까요?',
        link: { text: 'Can we move‿our call to 4?', sound: 'kən wee MOO-var CALL tə FOUR', rules: ['weak', 'link'] } },
      { en: 'Can we move it up an hour?', ko: '한 시간 앞당길 수 있을까요?',
        link: { text: 'Can we move‿it‿up‿an‿hour?', sound: 'kən wee MOO-vi-DUH-pə-NOUR', rules: ['weak', 'link', 'flap'] } }],
    roleplay: { tutor: "So we're meeting tomorrow at 10, right?", ko: '그럼 내일 10시에 회의하는 거 맞죠?', answer: 'Actually, can we move it to 11? Something came up.' } },
  { id: 'im-available', cat: 'office', sit: '일정 조율', tone: 'neutral', pattern: "I'm available ___.", key: "i'm available",
    ko: '~ 시간 돼요', when: '가능한 시간을 알려줄 때',
    variants: [
      { en: "I'm available all afternoon.", ko: '오후 내내 시간 돼요.',
        link: { text: "I'm‿available‿all‿afternoon.", sound: 'ai-mə-VAY-lə-bə-LAW-laf-tər-NOON', rules: ['link'] } },
      { en: "I'm available after 2.", ko: '2시 이후에 시간 돼요.',
        link: { text: "I'm‿available‿after 2.", sound: 'ai-mə-VAY-lə-bə-LAF-tər TOO', rules: ['link'] } },
      { en: "I'm available anytime on Monday.", ko: '월요일엔 아무 때나 괜찮아요.',
        link: { text: "I'm‿available‿anytime‿on Monday.", sound: 'ai-mə-VAY-lə-bə-LE-nee-tai-mon MUN-day', rules: ['link'] } }],
    roleplay: { tutor: 'When are you free to go over the slides?', ko: '발표 자료 같이 볼 시간 언제 돼요?', answer: "I'm available all afternoon." } },
  { id: 'can-you-see', cat: 'office', sit: '화상회의', tone: 'neutral', pattern: 'Can you see ___?', key: 'can you see',
    ko: '~ 보이세요?', when: '화면 공유 중에 잘 보이는지 확인할 때',
    variants: [
      { en: 'Can you see my screen?', ko: '제 화면 보이세요?',
        link: { text: 'Can you see my screen?', sound: 'kən-yə SEE mai SKREEN', rules: ['weak'] } },
      { en: 'Can you see the slides?', ko: '슬라이드 보이세요?',
        link: { text: 'Can you see the slides?', sound: 'kən-yə SEE thə SLIDEZ', rules: ['weak'] } },
      { en: 'Can everyone see this?', ko: '다들 보이세요?',
        link: { text: 'Can‿everyone see this?', sound: 'kə-NEV-ree-wən SEE THIS', rules: ['link', 'weak'] } }],
    roleplay: { tutor: 'Okay, go ahead and share your screen.', ko: '네, 화면 공유해 주세요.', answer: 'Sure. Can you see my screen?' } },
  { id: 'sorry-you', cat: 'office', sit: '화상회의', tone: 'casual', pattern: 'Sorry, you ___.', key: 'sorry you',
    ko: '죄송한데, ~', when: '상대의 연결 상태를 알려줄 때',
    variants: [
      { en: 'Sorry, you cut out for a second.', ko: '죄송한데 잠깐 끊겼어요.',
        link: { text: 'Sorry, you cut‿out for‿a second.', sound: 'SA-ree, yu KUH-DOUT fə-rə SE-kənd', rules: ['flap', 'link', 'weak'] } },
      { en: "Sorry, you're on mute.", ko: '죄송한데 음소거 되어 있어요.',
        link: { text: "Sorry, you're‿on mute.", sound: 'SA-ree, yər-RON MYOOT', rules: ['link'] } },
      { en: 'Sorry, you froze.', ko: '죄송한데 화면이 멈췄어요.',
        link: { text: 'Sorry, you froze.', sound: 'SA-ree, yu FROHZ', rules: [] } }],
    roleplay: { tutor: "…and that's why the numbers went up. Any questions?", ko: '…그래서 수치가 오른 거예요. 질문 있어요?', answer: 'Sorry, you cut out for a second. Could you repeat that?' } },
  { id: 'let-me-share', cat: 'office', sit: '화상회의', tone: 'neutral', pattern: 'Let me share ___.', key: 'let me share',
    ko: '~ 공유할게요', when: '화면이나 자료를 공유할 때',
    tip: 'deck은 외국계 회사에서 발표 자료(슬라이드)를 가리키는 말이에요.',
    variants: [
      { en: 'Let me share my screen.', ko: '제 화면 공유할게요.',
        link: { text: 'Le(t) me share my screen.', sound: 'le(t) mee SHARE mai SKREEN', rules: ['stop'] } },
      { en: 'Let me share the link in the chat.', ko: '채팅창에 링크 공유할게요.',
        link: { text: 'Le(t) me share the link‿in the chat.', sound: 'le(t) mee SHARE thə LING-kin thə CHAT', rules: ['stop', 'link'] } },
      { en: 'Let me share the deck real quick.', ko: '발표 자료 잠깐 공유할게요.',
        link: { text: 'Le(t) me share the deck real quick.', sound: 'le(t) mee SHARE thə DECK REEL KWICK', rules: ['stop'] } }],
    roleplay: { tutor: 'Can you walk us through the numbers?', ko: '수치 좀 설명해 줄래요?', answer: 'Sure, let me share my screen.' } },
);
