CARDS.push(
  { id: 'let-me-check', cat: 'service', sit: '안내·설명', tone: 'polite', pattern: 'Let me check ___ for you.', key: 'let me check',
    ko: '확인해 드릴게요', when: '바로 답하기 어려울 때 시간을 버는 표현',
    variants: [
      { en: 'Let me check that for you.', ko: '확인해 드릴게요.',
        link: { text: 'Le(t) me check tha(t) for you.', sound: 'le(t) mee CHECK tha(t) fər yu', rules: ['stop', 'weak'] } },
      { en: 'Let me check if we have it in stock.', ko: '재고가 있는지 확인해 볼게요.',
        link: { text: 'Le(t) me check‿if we have‿it‿in stock.', sound: 'le(t) mee CHE-kif wee HA-vi-din STOCK', rules: ['stop', 'link', 'flap'] } },
      { en: 'Let me check with my manager.', ko: '매니저에게 확인해 볼게요.',
        link: { text: 'Le(t) me check with my manager.', sound: 'le(t) mee CHECK with mai MA-nə-jər', rules: ['stop'] } }],
    roleplay: { tutor: 'Do you have this jacket in a medium?', ko: '이 재킷 M 사이즈 있어요?', answer: 'Let me check if we have it in stock.' } },
  { id: 'sorry-for', cat: 'service', sit: '사과·불만 대응', tone: 'polite', pattern: "I'm sorry for ___.", key: ["i'm sorry", "i'm so sorry", 'i apologize'],
    ko: '~해서 죄송합니다', when: '고객에게 사과할 때',
    tip: '"I apologize for ___"가 더 격식 있어요.',
    variants: [
      { en: "I'm sorry for the wait.", ko: '기다리게 해서 죄송합니다.',
        link: { text: "I'm sorry for the wait.", sound: 'aim SA-ree fər thə WAIT', rules: ['weak'] } },
      { en: 'I apologize for the inconvenience.', ko: '불편을 드려 죄송합니다.',
        link: { text: 'I‿apologize for the‿inconvenience.', sound: 'ai-yə-PA-lə-jaiz fər thee-yin-kən-VEE-nyəns', rules: ['glide', 'weak'] } },
      { en: "I'm sorry about the mix-up.", ko: '착오가 있었네요. 죄송합니다.',
        link: { text: "I'm sorry‿abou(t) the mix-up.", sound: 'aim SA-ree-yə-BOU(t) thə MIK-sup', rules: ['glide', 'stop', 'link'] } }],
    roleplay: { tutor: "I've been waiting here for twenty minutes!", ko: '여기서 20분이나 기다렸어요!', answer: "I'm so sorry for the wait. Let me check on your order." } },
  { id: 'it-should', cat: 'service', sit: '안내·설명', tone: 'polite', pattern: 'It should ___.', key: 'it should',
    ko: '~일 거예요', when: '시간이나 절차를 안내할 때',
    tip: '"It will"보다 덜 단정적이라, 약속을 못 지킬 위험이 줄어요.',
    variants: [
      { en: 'It should take about 10 minutes.', ko: '10분 정도 걸릴 거예요.',
        link: { text: 'I(t) should take‿abou(t) 10 minutes.', sound: 'i(t) shəd TAY-kə-BOU(t) TEN MI-nits', rules: ['stop', 'link'] } },
      { en: 'It should be ready by 3.', ko: '3시까지는 준비될 거예요.',
        link: { text: 'I(t) should be ready by 3.', sound: 'i(t) shəd bee RE-dee bai THREE', rules: ['stop'] } },
      { en: 'It should arrive within a week.', ko: '일주일 안에 도착할 거예요.',
        link: { text: 'I(t) should‿arrive within‿a week.', sound: 'i(t) shə-də-RAIV wi-thi-nə WEEK', rules: ['stop', 'link', 'weak'] } }],
    roleplay: { tutor: 'How long will it take to fix my phone?', ko: '폰 고치는 데 얼마나 걸려요?', answer: 'It should take about an hour.' } },
  { id: 'would-you-like', cat: 'service', sit: '결제·마무리', tone: 'polite', pattern: 'Would you like ___?', key: 'would you like',
    ko: '~ 하시겠어요?', when: '고객에게 뭔가를 제안할 때',
    variants: [
      { en: 'Would you like a receipt?', ko: '영수증 드릴까요?',
        link: { text: 'Would you like‿a receipt?', sound: 'wu-jə LAI-kə ri-SEET', rules: ['yu', 'link', 'weak'] } },
      { en: 'Would you like me to call you a taxi?', ko: '택시 불러 드릴까요?',
        link: { text: 'Would you like me to call you‿a taxi?', sound: 'wu-jə LAIK mee tə CALL yu-wə TAK-see', rules: ['yu', 'weak', 'glide'] } },
      { en: 'Would you like to wait here?', ko: '여기서 기다리시겠어요?',
        link: { text: 'Would you like to wai(t) here?', sound: 'wu-jə LAIK tə WAI(t) HEER', rules: ['yu', 'weak', 'stop'] } }],
    roleplay: { tutor: "Okay, I'll take this one.", ko: '이걸로 할게요.', answer: 'Great choice! Would you like a bag?' } },
  { id: 'could-i-get-your', cat: 'service', sit: '맞이하기·용건 확인', tone: 'polite', pattern: 'Could I get your ___?', key: 'could i get your',
    ko: '~ 알려주시겠어요?', when: '고객 정보를 요청할 때',
    variants: [
      { en: 'Could I get your name, please?', ko: '성함 알려주시겠어요?',
        link: { text: 'Could‿I get‿your name, please?', sound: 'ku-dai GE-chər NAME, PLEEZ', rules: ['link', 'yu'] } },
      { en: 'Could I get your phone number?', ko: '전화번호 알려주시겠어요?',
        link: { text: 'Could‿I get‿your phone number?', sound: 'ku-dai GE-chər FOHN NUM-bər', rules: ['link', 'yu'] } },
      { en: 'Could I get your reservation number?', ko: '예약 번호 알려주시겠어요?',
        link: { text: 'Could‿I get‿your reservation number?', sound: 'ku-dai GE-chər re-zər-VAY-shən NUM-bər', rules: ['link', 'yu'] } }],
    roleplay: { tutor: 'Hi, I have a reservation for tonight.', ko: '오늘 밤 예약했는데요.', answer: 'Sure. Could I get your name, please?' } },
  { id: 'are-you-looking-for', cat: 'service', sit: '맞이하기·용건 확인', tone: 'polite', pattern: 'Are you looking for ___?', key: 'are you looking for',
    ko: '~ 찾으세요?', when: '손님에게 먼저 다가가 도움을 제안할 때',
    tip: '"Can I help you?"만 반복하는 것보다 구체적으로 물으면 대화가 이어지기 쉬워요.',
    variants: [
      { en: 'Are you looking for anything in particular?', ko: '특별히 찾으시는 거 있으세요?',
        link: { text: 'Are you looking for‿anything‿in particular?', sound: 'ar yu LOO-king fə-RE-nee-thing-in pər-TI-kyə-lər', rules: ['link', 'weak'] } },
      { en: 'Are you looking for a gift?', ko: '선물 찾으세요?',
        link: { text: 'Are you looking for‿a gift?', sound: 'ar yu LOO-king fə-rə GIFT', rules: ['link', 'weak'] } },
      { en: 'Are you looking for a specific size?', ko: '찾으시는 사이즈 있으세요?',
        link: { text: 'Are you looking for‿a specific size?', sound: 'ar yu LOO-king fə-rə spə-SI-fik SIZE', rules: ['link', 'weak'] } }],
    roleplay: { tutor: 'Hi! Wow, you have a lot of jackets here.', ko: '안녕하세요! 와, 재킷이 많네요.', answer: 'We do! Are you looking for a specific size?' } },
  { id: 'first-time', cat: 'service', sit: '맞이하기·용건 확인', tone: 'polite', pattern: 'Is this your first time ___?', key: 'is this your first time',
    ko: '~ 처음이세요?', when: '처음 온 손님인지 확인할 때',
    variants: [
      { en: 'Is this your first time here?', ko: '여기 처음 오셨어요?',
        link: { text: 'Is this your firs(t) time here?', sound: 'iz this yər FIRS(t) TIME HEER', rules: ['weak', 'same'] } },
      { en: 'Is this your first time staying with us?', ko: '저희 호텔 처음 이용하세요?',
        link: { text: 'Is this your firs(t) time staying with‿us?', sound: 'iz this yər FIRS(t) TIME STAY-ing wi-thəs', rules: ['weak', 'same', 'link'] } },
      { en: 'Is this your first time trying our coffee?', ko: '저희 커피 처음 드셔 보세요?',
        link: { text: 'Is this your firs(t) time trying‿our coffee?', sound: 'iz this yər FIRS(t) TIME TRAI-ing-ar KAW-fee', rules: ['weak', 'same', 'link'] } }],
    roleplay: { tutor: 'Hi, um… how does this work?', ko: '안녕하세요, 음… 이거 어떻게 하는 거예요?', answer: 'No problem! Is this your first time here?' } },
  { id: 'it-comes-with', cat: 'service', sit: '안내·설명', tone: 'polite', pattern: 'It comes with ___.', key: 'it comes with',
    ko: '~가 포함돼 있어요', when: '상품이나 메뉴에 무엇이 포함되는지 설명할 때',
    variants: [
      { en: 'It comes with free Wi-Fi.', ko: '무료 와이파이가 포함돼 있어요.',
        link: { text: 'I(t) comes with free Wi-Fi.', sound: 'i(t) KUMZ with FREE WAI-fai', rules: ['stop'] } },
      { en: 'It comes with a side salad.', ko: '사이드 샐러드가 같이 나와요.',
        link: { text: 'I(t) comes with‿a side salad.', sound: 'i(t) KUMZ wi-thə SIDE SA-ləd', rules: ['stop', 'link', 'weak'] } },
      { en: 'It comes with a one-year warranty.', ko: '1년 보증이 포함돼 있어요.',
        link: { text: 'I(t) comes with‿a one-year warranty.', sound: 'i(t) KUMZ wi-thə WUN-yeer WOR-ən-tee', rules: ['stop', 'link', 'weak'] } }],
    roleplay: { tutor: "What's included in the room price?", ko: '객실 요금에 뭐가 포함돼 있어요?', answer: 'It comes with breakfast and free Wi-Fi.' } },
  { id: 'could-you-wait', cat: 'service', sit: '기다리게 할 때', tone: 'polite', pattern: 'Could you wait ___?', key: 'could you wait',
    ko: '~ 기다려 주시겠어요?', when: '손님에게 잠시 기다려 달라고 할 때',
    tip: '기다리게 한 뒤에는 "Thank you for waiting."으로 이어가면 자연스러워요.',
    variants: [
      { en: 'Could you wait here for a moment?', ko: '여기서 잠시만 기다려 주시겠어요?',
        link: { text: 'Could you wai(t) here for‿a moment?', sound: 'ku-jə WAI(t) HEER fə-rə MOH-mənt', rules: ['yu', 'stop', 'link', 'weak'] } },
      { en: 'Could you wait just a few minutes?', ko: '몇 분만 기다려 주시겠어요?',
        link: { text: 'Could you wai(t) just‿a few minutes?', sound: 'ku-jə WAI(t) jəs-tə FEW MI-nits', rules: ['yu', 'stop', 'link'] } },
      { en: 'Could you wait by the counter?', ko: '카운터 옆에서 기다려 주시겠어요?',
        link: { text: 'Could you wai(t) by the counter?', sound: 'ku-jə WAI(t) bai thə KAUN-tər', rules: ['yu', 'stop', 'weak'] } }],
    roleplay: { tutor: "Hi, I'm here to pick up my order.", ko: '안녕하세요, 주문한 거 찾으러 왔어요.', answer: 'Sure. Could you wait here for a moment?' } },
  { id: 'someone-will', cat: 'service', sit: '기다리게 할 때', tone: 'polite', pattern: 'Someone will ___ shortly.', key: 'someone will',
    ko: '곧 ~해 드릴 거예요', when: '곧 담당자가 처리한다고 안내할 때',
    variants: [
      { en: 'Someone will be with you shortly.', ko: '곧 담당자가 도와드릴 거예요.',
        link: { text: 'Someone will be with you shortly.', sound: 'SUM-wən wəl bee WITH yu SHORT-lee', rules: ['weak'] } },
      { en: 'Someone will bring it out shortly.', ko: '곧 가져다드릴 거예요.',
        link: { text: 'Someone will bring‿it‿out shortly.', sound: 'SUM-wən wəl BRING-i-DOUT SHORT-lee', rules: ['weak', 'link', 'flap'] } },
      { en: 'Someone will call you shortly.', ko: '곧 전화드릴 거예요.',
        link: { text: 'Someone will call you shortly.', sound: 'SUM-wən wəl CALL yu SHORT-lee', rules: ['weak'] } }],
    roleplay: { tutor: "Excuse me, we've been waiting for our food for a while.", ko: '저기요, 음식을 꽤 오래 기다리고 있는데요.', answer: "I'm sorry about that. Someone will bring it out shortly." } },
  { id: 'thank-you-for', cat: 'service', sit: '기다리게 할 때', tone: 'polite', pattern: 'Thank you for ___.', key: 'thank you for',
    ko: '~해 주셔서 감사합니다', when: '기다려 준 손님에게 인사할 때',
    tip: '기다리게 했을 때는 "Sorry for the wait"보다 "Thank you for your patience"가 더 긍정적으로 들려요.',
    variants: [
      { en: 'Thank you for waiting.', ko: '기다려 주셔서 감사합니다.',
        link: { text: 'Thank‿you for waiting.', sound: 'THANK-yu fər WAY-ding', rules: ['link', 'weak', 'flap'] } },
      { en: 'Thank you for your patience.', ko: '양해해 주셔서 감사합니다.',
        link: { text: 'Thank‿you for your patience.', sound: 'THANK-yu fər yər PAY-shəns', rules: ['link', 'weak'] } },
      { en: 'Thank you for letting us know.', ko: '알려 주셔서 감사합니다.',
        link: { text: 'Thank‿you for letting‿us know.', sound: 'THANK-yu fər LE-ding-əs KNOW', rules: ['link', 'weak', 'flap'] } }],
    roleplay: { tutor: 'Is my table ready yet?', ko: '제 테이블 준비됐어요?', answer: 'Yes, it is. Thank you for waiting!' } },
  { id: 'i-understand', cat: 'service', sit: '사과·불만 대응', tone: 'polite', pattern: 'I understand ___.', key: 'i understand',
    ko: '~ 이해합니다', when: '화가 난 손님에게 먼저 공감할 때',
    tip: '불만을 들으면 설명보다 공감을 먼저 하세요. 그다음에 해결책을 말하면 훨씬 부드러워요.',
    variants: [
      { en: 'I understand how frustrating that is.', ko: '얼마나 답답하셨을지 이해합니다.',
        link: { text: 'I‿understand how frustrating that‿is.', sound: 'ai-yən-dər-STAND hau FRUS-tray-ding tha-DIZ', rules: ['glide', 'flap'] } },
      { en: 'I understand your concern.', ko: '걱정하시는 부분 이해합니다.',
        link: { text: 'I‿understand your concern.', sound: 'ai-yən-dər-STAND yər kən-SURN', rules: ['glide', 'weak'] } },
      { en: 'I understand. Let me see what I can do.', ko: '이해합니다. 제가 할 수 있는 걸 알아볼게요.',
        link: { text: 'I‿understand. Le(t) me see what‿I can do.', sound: 'ai-yən-dər-STAND. le(t) mee SEE wə-dai kən DOO', rules: ['glide', 'stop', 'flap', 'weak'] } }],
    roleplay: { tutor: 'This is the second time my order has been wrong!', ko: '주문이 잘못 나온 게 벌써 두 번째예요!', answer: 'I understand how frustrating that is. Let me fix it right away.' } },
  { id: 'what-i-can-do', cat: 'service', sit: '사과·불만 대응', tone: 'polite', pattern: 'What I can do is ___.', key: 'what i can do',
    ko: '제가 해 드릴 수 있는 건 ~예요', when: '요청을 그대로 들어줄 수 없을 때 대안을 제시할 때',
    tip: '"We can\'t ~"로 시작하는 것보다 할 수 있는 걸 먼저 말하면 거절처럼 들리지 않아요.',
    variants: [
      { en: 'What I can do is give you a refund.', ko: '환불해 드릴 수 있어요.',
        link: { text: 'What‿I can do‿is give you‿a refund.', sound: 'wə-dai kən DOO-wiz GIV yu-wə REE-fund', rules: ['flap', 'weak', 'glide'] } },
      { en: 'What I can do is offer you a discount.', ko: '할인해 드릴 수 있어요.',
        link: { text: 'What‿I can do‿is‿offer you‿a discount.', sound: 'wə-dai kən DOO-wi-ZAW-fər yu-wə DIS-kount', rules: ['flap', 'weak', 'glide', 'link'] } },
      { en: 'What I can do is exchange it for a new one.', ko: '새 제품으로 교환해 드릴 수 있어요.',
        link: { text: 'What‿I can do‿is‿exchange‿it for‿a new one.', sound: 'wə-dai kən DOO-wi-zeks-CHAIN-jit fə-rə NEW WUN', rules: ['flap', 'weak', 'glide', 'link'] } }],
    roleplay: { tutor: 'I lost my receipt. Can I still get my money back?', ko: '영수증을 잃어버렸는데, 그래도 환불돼요?', answer: "I'm sorry, we need a receipt for refunds. What I can do is exchange it for a new one." } },
  { id: 'will-that-be', cat: 'service', sit: '결제·마무리', tone: 'polite', pattern: 'Will that be ___?', key: 'will that be',
    ko: '~로 하시겠어요?', when: '결제 방식이나 주문 마무리를 확인할 때',
    variants: [
      { en: 'Will that be cash or card?', ko: '현금으로 하시겠어요, 카드로 하시겠어요?',
        link: { text: 'Will tha(t) be cash‿or card?', sound: 'wəl tha(t) bee KA-shər CARD', rules: ['stop', 'link', 'weak'] } },
      { en: 'Will that be all for today?', ko: '오늘은 이게 다인가요?',
        link: { text: 'Will tha(t) be‿all for today?', sound: 'wəl tha(t) bee-YAWL fər tə-DAY', rules: ['stop', 'glide', 'weak'] } },
      { en: 'Will that be for here or to go?', ko: '드시고 가세요, 가져가세요?',
        link: { text: 'Will tha(t) be for here‿or to go?', sound: 'wəl tha(t) bee fər HEE-rər tə GO', rules: ['stop', 'link', 'weak'] } }],
    roleplay: { tutor: "I'll take these two shirts.", ko: '이 셔츠 두 장 살게요.', answer: 'Great! Will that be cash or card?' } },
  { id: 'have-a', cat: 'service', sit: '결제·마무리', tone: 'casual', pattern: 'Have a ___!', key: 'have a',
    ko: '좋은 ~ 보내세요!', when: '손님을 배웅할 때',
    tip: '손님이 "You too!"라고 답하는 경우가 많아요. 반대로 이 말을 들으면 "You too!"라고 답하면 돼요.',
    variants: [
      { en: 'Have a great day!', ko: '좋은 하루 보내세요!',
        link: { text: 'Have‿a grea(t) day!', sound: 'HA-və GREA(t) DAY', rules: ['link', 'weak', 'stop'] } },
      { en: 'Have a nice evening!', ko: '좋은 저녁 보내세요!',
        link: { text: 'Have‿a nice‿evening!', sound: 'HA-və NAI-SEEV-ning', rules: ['link', 'weak'] } },
      { en: 'Have a safe trip!', ko: '조심히 가세요!',
        link: { text: 'Have‿a safe trip!', sound: 'HA-və SAFE TRIP', rules: ['link', 'weak'] } }],
    roleplay: { tutor: 'Thanks for your help!', ko: '도와주셔서 고마워요!', answer: 'My pleasure. Have a great day!' } },
);
