CARDS.push(
  { id: 'is-there-around', cat: 'travel', sit: '길 찾기·교통', tone: 'neutral', pattern: 'Is there ___ around here?', key: 'is there',
    ko: '이 근처에 ~ 있어요?', when: '길에서 장소를 찾을 때',
    variants: [
      { en: 'Is there a pharmacy around here?', ko: '이 근처에 약국 있어요?' },
      { en: 'Is there a subway station nearby?', ko: '근처에 지하철역 있어요?' },
      { en: 'Is there a good place to eat around here?', ko: '이 근처에 괜찮은 식당 있어요?' }],
    roleplay: { tutor: 'Hi there, can I help you with something?', ko: '도와드릴까요?', answer: 'Yes, is there an ATM around here?' } },
  { id: 'how-do-i-get-to', cat: 'travel', sit: '길 찾기·교통', tone: 'neutral', pattern: 'How do I get to ___?', key: 'how do i get to',
    ko: '~에 어떻게 가요?', when: '길을 물을 때',
    variants: [
      { en: 'How do I get to the airport?', ko: '공항에 어떻게 가요?' },
      { en: 'How do I get to Times Square from here?', ko: '여기서 타임스스퀘어 어떻게 가요?' },
      { en: 'How do I get to Gate 12?', ko: '12번 게이트 어떻게 가요?' }],
    roleplay: { tutor: 'You look lost. Where are you headed?', ko: '길 잃으신 것 같네요. 어디 가세요?', answer: 'How do I get to Central Park?' } },
  { id: 'id-like-to', cat: 'travel', sit: '호텔', tone: 'polite', pattern: "I'd like to ___.", key: "i'd like to",
    ko: '~하고 싶습니다', when: '호텔·공항에서 요청할 때',
    tip: '"I want to ___"보다 정중해요. 호텔·공항에서는 이걸 기본으로 쓰세요.',
    variants: [
      { en: "I'd like to check in.", ko: '체크인하려고요.' },
      { en: "I'd like to change my seat.", ko: '좌석을 바꾸고 싶어요.' },
      { en: "I'd like to stay one more night.", ko: '하룻밤 더 묵고 싶어요.' }],
    roleplay: { tutor: 'Good evening! How can I help you?', ko: '안녕하세요! 무엇을 도와드릴까요?', answer: "Hi, I'd like to check in. The reservation is under Kim." } },
  { id: 'is-it-okay-if', cat: 'travel', sit: '호텔', tone: 'neutral', pattern: 'Is it okay if ___?', key: 'is it okay if',
    ko: '~해도 괜찮을까요?', when: '허락을 구할 때',
    variants: [
      { en: 'Is it okay if I leave my bags here?', ko: '짐을 여기 둬도 될까요?',
        link: { text: 'Is‿it‿okay‿if‿I leave my bags here?', sound: 'i-zi-dou-KAY-yi-fai LEAVE mai BAGZ heer', rules: ['link', 'flap', 'glide'] } },
      { en: 'Is it okay if I sit here?', ko: '여기 앉아도 될까요?',
        link: { text: 'Is‿it‿okay‿if‿I si(t) here?', sound: 'i-zi-dou-KAY-yi-fai SI(t) heer', rules: ['link', 'flap', 'glide', 'stop'] } },
      { en: 'Is it okay if I pay by card?', ko: '카드로 계산해도 될까요?',
        link: { text: 'Is‿it‿okay‿if‿I pay by card?', sound: 'i-zi-dou-KAY-yi-fai PAY bai CARD', rules: ['link', 'flap', 'glide'] } }],
    roleplay: { tutor: 'Checkout is at 11. Anything else?', ko: '체크아웃은 11시예요. 더 필요하신 거 있으세요?', answer: 'Is it okay if I leave my bags here after checkout?' } },
  { id: 'problem-with', cat: 'travel', sit: '문제 생겼을 때', tone: 'polite', pattern: "I think there's a problem with ___.", key: "there's a problem with",
    ko: '~에 문제가 있는 것 같아요', when: '방, 예약, 계산서에 문제가 있을 때',
    tip: '"I think"로 시작하면 따지는 느낌이 줄어요.',
    variants: [
      { en: "I think there's a problem with my room.", ko: '방에 문제가 있는 것 같아요.' },
      { en: "I think there's a problem with my reservation.", ko: '예약에 문제가 있는 것 같아요.' },
      { en: "I think there's a problem with the bill.", ko: '계산서가 잘못된 것 같아요.' }],
    roleplay: { tutor: 'Is everything okay with your stay?', ko: '지내시는 데 불편한 건 없으세요?', answer: "Actually, I think there's a problem with the air conditioner." } },
  { id: 'line-for', cat: 'travel', sit: '공항·기내', tone: 'neutral', pattern: 'Is this the line for ___?', key: 'is this the line',
    ko: '~ 줄이 여기 맞아요?', when: '공항이나 관광지에서 줄을 제대로 섰는지 확인할 때',
    variants: [
      { en: 'Is this the line for security?', ko: '보안 검색 줄 여기 맞아요?',
        link: { text: 'Is this the line for security?', sound: 'iz THIS thə LINE fər sə-KYUR-ə-dee', rules: ['weak', 'flap'] } },
      { en: 'Is this the line for check-in?', ko: '체크인 줄 여기 맞아요?',
        link: { text: 'Is this the line for check‿in?', sound: 'iz THIS thə LINE fər CHE-kin', rules: ['weak', 'link'] } },
      { en: 'Is this the line for the shuttle?', ko: '셔틀 타는 줄 여기 맞아요?',
        link: { text: 'Is this the line for the shuttle?', sound: 'iz THIS thə LINE fər thə SHUH-dəl', rules: ['weak', 'flap'] } }],
    roleplay: { tutor: 'Excuse me, are you in line?', ko: '실례지만, 줄 서 계신 거예요?', answer: 'Yes. Is this the line for check-in?' } },
  { id: 'im-staying', cat: 'travel', sit: '공항·기내', tone: 'neutral', pattern: "I'm staying ___.", key: "i'm staying",
    ko: '~에 묵어요 / ~ 동안 머물러요', when: '입국 심사에서 숙소나 기간을 물을 때',
    tip: '입국 심사에서는 짧고 분명하게 답하는 게 좋아요. 숙소 이름을 미리 외워 두세요.',
    variants: [
      { en: "I'm staying at the Hilton downtown.", ko: '시내 힐튼 호텔에 묵어요.',
        link: { text: "I'm staying‿at the Hilton downtown.", sound: 'aim STAY-ing-ət thə HIL-tən down-TOWN', rules: ['link', 'weak'] } },
      { en: "I'm staying for ten days.", ko: '열흘 동안 머물러요.',
        link: { text: "I'm staying for ten days.", sound: 'aim STAY-ing fər TEN DAYZ', rules: ['weak'] } },
      { en: "I'm staying with a friend.", ko: '친구 집에 묵어요.',
        link: { text: "I'm staying with‿a friend.", sound: 'aim STAY-ing wi-thə FREND', rules: ['link', 'weak'] } }],
    roleplay: { tutor: 'Where will you be staying?', ko: '어디서 묵으실 건가요?', answer: "I'm staying at the Hilton downtown." } },
  { id: 'would-it-be-possible', cat: 'travel', sit: '공항·기내', tone: 'polite', pattern: 'Would it be possible to ___?', key: 'would it be possible',
    ko: '~할 수 있을까요?', when: '카운터나 기내에서 정중하게 요청할 때',
    tip: '"Can I ~?"보다 한 단계 더 정중해요. 들어주기 어려운 부탁일수록 이걸 쓰세요.',
    variants: [
      { en: 'Would it be possible to get an aisle seat?', ko: '통로 쪽 좌석으로 받을 수 있을까요?',
        link: { text: 'Would‿i(t) be possible to get‿an‿aisle seat?', sound: 'wu-di(t) bee PA-sə-bəl tə ge-də-NAIL SEAT', rules: ['link', 'stop', 'weak', 'flap'] } },
      { en: 'Would it be possible to switch seats?', ko: '자리를 바꿀 수 있을까요?',
        link: { text: 'Would‿i(t) be possible to switch seats?', sound: 'wu-di(t) bee PA-sə-bəl tə SWITCH SEATS', rules: ['link', 'stop', 'weak'] } },
      { en: 'Would it be possible to get an extra blanket?', ko: '담요 하나 더 받을 수 있을까요?',
        link: { text: 'Would‿i(t) be possible to get‿an‿extra blanket?', sound: 'wu-di(t) bee PA-sə-bəl tə ge-də-NEK-strə BLAN-kit', rules: ['link', 'stop', 'weak', 'flap'] } }],
    roleplay: { tutor: "Here's your boarding pass. Anything else?", ko: '탑승권 여기 있습니다. 더 필요하신 거 있으세요?', answer: 'Would it be possible to get an aisle seat?' } },
  { id: 'what-time-does', cat: 'travel', sit: '호텔', tone: 'neutral', pattern: 'What time does ___?', key: 'what time does',
    ko: '~ 몇 시에 해요?', when: '호텔 시설이나 교통편 시간을 물을 때',
    variants: [
      { en: 'What time does breakfast start?', ko: '조식은 몇 시에 시작해요?',
        link: { text: 'Wha(t) time does breakfast start?', sound: 'wə TIME dəz BREK-fəst START', rules: ['same', 'weak'] } },
      { en: 'What time does the pool close?', ko: '수영장은 몇 시에 닫아요?',
        link: { text: 'Wha(t) time does the pool close?', sound: 'wə TIME dəz thə POOL CLOSE', rules: ['same', 'weak'] } },
      { en: 'What time does the shuttle leave?', ko: '셔틀은 몇 시에 출발해요?',
        link: { text: 'Wha(t) time does the shuttle leave?', sound: 'wə TIME dəz thə SHUH-dəl LEAVE', rules: ['same', 'weak', 'flap'] } }],
    roleplay: { tutor: "Here's your key card. Enjoy your stay!", ko: '키 카드 여기 있습니다. 즐거운 시간 되세요!', answer: 'Thanks! What time does breakfast start?' } },
  { id: 'which-should-i-take', cat: 'travel', sit: '길 찾기·교통', tone: 'neutral', pattern: 'Which ___ should I take?', key: 'should i take',
    ko: '어느 ~를 타야 해요?', when: '버스·지하철 노선이나 출구를 고를 때',
    variants: [
      { en: 'Which bus should I take to get downtown?', ko: '시내 가려면 어느 버스 타야 해요?',
        link: { text: 'Which bus should‿I take to ge(t) downtown?', sound: 'wich BUS shu-dai TAKE tə ge(t) down-TOWN', rules: ['link', 'weak', 'stop'] } },
      { en: 'Which exit should I take?', ko: '어느 출구로 나가야 해요?',
        link: { text: 'Which‿exit should‿I take?', sound: 'wi-CHEK-sit shu-dai TAKE', rules: ['link'] } },
      { en: 'Which line should I take to the airport?', ko: '공항 가려면 몇 호선 타야 해요?',
        link: { text: 'Which line should‿I take to the‿airport?', sound: 'wich LINE shu-dai TAKE tə thee-YAIR-port', rules: ['link', 'weak', 'glide'] } }],
    roleplay: { tutor: "You want to go to the museum? It's pretty far from here.", ko: '박물관 가시려고요? 여기서 꽤 멀어요.', answer: 'Oh really? Which bus should I take?' } },
  { id: 'do-i-need', cat: 'travel', sit: '관광·예약', tone: 'neutral', pattern: 'Do I need ___?', key: 'do i need',
    ko: '~ 필요해요?', when: '예약이나 표가 필요한지 물을 때',
    variants: [
      { en: 'Do I need a reservation?', ko: '예약해야 하나요?',
        link: { text: 'Do‿I need‿a reservation?', sound: 'də-wai NEE-də re-zər-VAY-shən', rules: ['glide', 'link'] } },
      { en: 'Do I need to book in advance?', ko: '미리 예약해야 하나요?',
        link: { text: 'Do‿I need to book‿in‿advance?', sound: 'də-wai NEE-tə BOO-kin-əd-VANCE', rules: ['glide', 'link', 'weak'] } },
      { en: 'Do I need a ticket for this?', ko: '이거 표가 필요해요?',
        link: { text: 'Do‿I need‿a ticket for this?', sound: 'də-wai NEE-də TI-kit fər THIS', rules: ['glide', 'link', 'weak'] } }],
    roleplay: { tutor: 'Welcome to the museum!', ko: '박물관에 오신 걸 환영해요!', answer: 'Hi! Do I need a ticket for the special exhibit?' } },
  { id: 'would-you-mind-taking', cat: 'travel', sit: '관광·예약', tone: 'neutral', pattern: 'Would you mind taking ___?', key: 'would you mind',
    ko: '~ 찍어 주실 수 있어요?', when: '사진을 부탁할 때',
    tip: '"Do you mind if I ~?"처럼 "No problem"이나 "Not at all"이 "괜찮아요, 해 줄게요"라는 뜻이에요.',
    variants: [
      { en: 'Would you mind taking a picture of us?', ko: '저희 사진 좀 찍어 주실래요?',
        link: { text: 'Would you mind taking‿a picture‿of‿us?', sound: 'wu-jə MIND TAY-king-ə PIK-chə-rə-vəs', rules: ['yu', 'link', 'weak'] } },
      { en: 'Would you mind taking one more?', ko: '한 장만 더 찍어 주실래요?',
        link: { text: 'Would you mind taking one more?', sound: 'wu-jə MIND TAY-king WUN MORE', rules: ['yu'] } },
      { en: 'Would you mind taking it vertically?', ko: '세로로 찍어 주실래요?',
        link: { text: 'Would you mind taking‿i(t) vertically?', sound: 'wu-jə MIND TAY-king-i(t) VER-di-klee', rules: ['yu', 'link', 'stop', 'flap'] } }],
    roleplay: { tutor: 'Wow, the view from up here is amazing!', ko: '와, 여기서 보는 경치 끝내준다!', answer: 'It really is! Would you mind taking a picture of us?' } },
  { id: 'how-long-take', cat: 'travel', sit: '관광·예약', tone: 'neutral', pattern: 'How long does ___ take?', key: 'how long does',
    ko: '~ 얼마나 걸려요?', when: '소요 시간을 물을 때',
    variants: [
      { en: 'How long does the tour take?', ko: '투어는 얼마나 걸려요?',
        link: { text: 'How long does the tour take?', sound: 'hau LONG dəz thə TOUR TAKE', rules: ['weak'] } },
      { en: 'How long does it take to get there by taxi?', ko: '택시로 거기까지 얼마나 걸려요?',
        link: { text: 'How long does‿i(t) take to ge(t) there by taxi?', sound: 'hau LONG də-zi(t) TAKE tə ge(t) THERE bai TAK-see', rules: ['link', 'stop', 'weak'] } },
      { en: 'How long does the ferry take?', ko: '페리는 얼마나 걸려요?',
        link: { text: 'How long does the ferry take?', sound: 'hau LONG dəz thə FE-ree TAKE', rules: ['weak'] } }],
    roleplay: { tutor: 'The boat tour leaves in ten minutes.', ko: '보트 투어는 10분 뒤에 출발해요.', answer: 'Great. How long does the tour take?' } },
  { id: 'i-lost', cat: 'travel', sit: '문제 생겼을 때', tone: 'neutral', pattern: 'I lost ___.', key: 'i lost',
    ko: '~를 잃어버렸어요', when: '물건을 잃어버렸을 때',
    tip: '분실물 센터를 찾을 때는 "Where\'s the lost and found?"라고 물어요.',
    variants: [
      { en: 'I lost my wallet.', ko: '지갑을 잃어버렸어요.',
        link: { text: 'I los(t) my wallet.', sound: 'ai LOS(t) mai WA-lit', rules: ['stop'] } },
      { en: 'I lost my passport.', ko: '여권을 잃어버렸어요.',
        link: { text: 'I los(t) my passport.', sound: 'ai LOS(t) mai PAS-port', rules: ['stop'] } },
      { en: 'I think I lost my phone on the bus.', ko: '버스에서 폰을 잃어버린 것 같아요.',
        link: { text: 'I think‿I los(t) my phone‿on the bus.', sound: 'ai THING-kai LOS(t) mai FOH-non thə BUS', rules: ['link', 'stop'] } }],
    roleplay: { tutor: 'Hi, what seems to be the problem?', ko: '무슨 문제 있으세요?', answer: 'I lost my passport. I think I left it in a taxi.' } },
  { id: 'i-missed', cat: 'travel', sit: '문제 생겼을 때', tone: 'neutral', pattern: 'I missed ___.', key: 'i missed',
    ko: '~를 놓쳤어요', when: '비행기나 교통편을 놓쳤을 때',
    tip: 'missed의 -ed는 [t]로 소리 나요. [미스드]가 아니라 [미스트]예요.',
    variants: [
      { en: 'I missed my flight.', ko: '비행기를 놓쳤어요.',
        link: { text: 'I missed my flight.', sound: 'ai MIS(t) mai FLIGHT', rules: ['stop'] } },
      { en: 'I missed my connection.', ko: '환승편을 놓쳤어요.',
        link: { text: 'I missed my connection.', sound: 'ai MIS(t) mai kə-NEK-shən', rules: ['stop', 'weak'] } },
      { en: 'I missed the last train.', ko: '막차를 놓쳤어요.',
        link: { text: 'I missed the las(t) train.', sound: 'ai MIS(t) thə LAS(t) TRAIN', rules: ['stop'] } }],
    roleplay: { tutor: 'Oh no, you look stressed. What happened?', ko: '어머, 당황하신 것 같네요. 무슨 일이에요?', answer: 'I missed my flight. When is the next one?' } },
);
